const ivFluidQuestions = [
  {
    id: "IVF-001",
    caseId: "IVF-CASE-001",
    patient: "Mr. Allen Brooks",
    topic: "IV Fluids",
    subtopic: "Isotonic Fluids",
    style: "Recognition",
    difficulty: "ATI",
    question: "Mr. Brooks is dehydrated after vomiting and diarrhea. The provider orders 0.9% normal saline. How should the nurse classify this fluid?",
    choices: ["Isotonic", "Hypotonic", "Hypertonic", "Colloid only"],
    answer: "Isotonic",
    rationale: "0.9% normal saline is isotonic and expands the intravascular space."
  },
  {
    id: "IVF-002",
    caseId: "IVF-CASE-001",
    patient: "Mr. Allen Brooks",
    topic: "IV Fluids",
    subtopic: "Isotonic Purpose",
    style: "Application",
    difficulty: "ATI",
    question: "Why is isotonic fluid appropriate for Mr. Brooks?",
    choices: ["It expands circulating volume", "It pulls fluid out of cells aggressively", "It causes immediate diuresis", "It lowers potassium directly"],
    answer: "It expands circulating volume",
    rationale: "Isotonic fluids stay mainly in the extracellular/intravascular space and are commonly used for fluid volume deficit."
  },
  {
    id: "IVF-003",
    caseId: "IVF-CASE-002",
    patient: "Ms. Carol Evans",
    topic: "IV Fluids",
    subtopic: "Hypotonic Fluids",
    style: "Recognition",
    difficulty: "ATI",
    question: "Ms. Evans has hypernatremia and dehydration. The provider orders 0.45% normal saline. How should the nurse classify this fluid?",
    choices: ["Hypotonic", "Isotonic", "Hypertonic", "Blood product"],
    answer: "Hypotonic",
    rationale: "0.45% normal saline is hypotonic and can move water into cells."
  },
  {
    id: "IVF-004",
    caseId: "IVF-CASE-002",
    patient: "Ms. Carol Evans",
    topic: "IV Fluids",
    subtopic: "Hypotonic Safety",
    style: "Safety",
    difficulty: "ATI",
    question: "Which patient should the nurse be most cautious about giving hypotonic fluids to?",
    choices: ["Patient with increased intracranial pressure", "Patient with mild dehydration", "Patient with hypernatremia", "Patient with dry mucous membranes"],
    answer: "Patient with increased intracranial pressure",
    rationale: "Hypotonic fluids can shift water into cells, which may worsen cerebral edema."
  },
  {
    id: "IVF-005",
    caseId: "IVF-CASE-003",
    patient: "Mr. Daniel Scott",
    topic: "IV Fluids",
    subtopic: "Hypertonic Fluids",
    style: "Recognition",
    difficulty: "ATI",
    question: "Mr. Scott has severe symptomatic hyponatremia. The provider orders 3% saline. How should the nurse classify this fluid?",
    choices: ["Hypertonic", "Hypotonic", "Isotonic", "Maintenance only"],
    answer: "Hypertonic",
    rationale: "3% saline is hypertonic and pulls fluid from cells into the intravascular space."
  },
  {
    id: "IVF-006",
    caseId: "IVF-CASE-003",
    patient: "Mr. Daniel Scott",
    topic: "IV Fluids",
    subtopic: "Hypertonic Safety",
    style: "Priority",
    difficulty: "ATI",
    question: "Mr. Scott is receiving 3% saline. What should the nurse monitor closely?",
    choices: ["Neurological status and sodium correction rate", "Hair growth", "Meal preference", "Bowel sounds only"],
    answer: "Neurological status and sodium correction rate",
    rationale: "Hypertonic saline must be administered carefully because rapid sodium correction can cause neurological injury."
  },
  {
    id: "IVF-007",
    caseId: "IVF-CASE-004",
    patient: "Ms. Hannah Lee",
    topic: "IV Fluids",
    subtopic: "Fluid Overload",
    style: "Analyze Cues",
    difficulty: "ATI",
    question: "Ms. Lee is receiving IV fluids and develops crackles, shortness of breath, and bounding pulses. Which complication is most likely?",
    choices: ["Fluid volume excess", "Hypokalemia", "Hypocalcemia", "Metabolic acidosis"],
    answer: "Fluid volume excess",
    rationale: "Crackles, dyspnea, bounding pulses, edema, and increased blood pressure may indicate fluid overload."
  },
  {
    id: "IVF-008",
    caseId: "IVF-CASE-004",
    patient: "Ms. Hannah Lee",
    topic: "IV Fluids",
    subtopic: "Priority",
    style: "Priority",
    difficulty: "ATI",
    question: "Ms. Lee develops respiratory distress while IV fluids are infusing. What should the nurse do first?",
    choices: ["Assess respiratory status and slow/stop fluids per protocol while notifying provider", "Increase IV rate", "Place her flat", "Encourage oral fluids"],
    answer: "Assess respiratory status and slow/stop fluids per protocol while notifying provider",
    rationale: "Respiratory distress from fluid overload is urgent. The nurse should prioritize breathing, prevent worsening overload, and notify the provider."
  },
  {
    id: "IVF-009",
    caseId: "IVF-CASE-005",
    patient: "Mr. Victor Grant",
    topic: "IV Fluids",
    subtopic: "Fluid Volume Deficit",
    style: "Recognition",
    difficulty: "ATI",
    question: "Mr. Grant has tachycardia, hypotension, dry mucous membranes, and poor skin turgor after diarrhea. Which problem is most likely?",
    choices: ["Fluid volume deficit", "Fluid volume excess", "Hypercalcemia", "Respiratory alkalosis"],
    answer: "Fluid volume deficit",
    rationale: "Tachycardia, hypotension, dry mucous membranes, poor skin turgor, and decreased urine output are signs of fluid volume deficit."
  },
  {
    id: "IVF-010",
    caseId: "IVF-CASE-005",
    patient: "Mr. Victor Grant",
    topic: "IV Fluids",
    subtopic: "Evaluation",
    style: "Evaluation",
    difficulty: "ATI",
    question: "Which finding indicates Mr. Grant's fluid volume deficit is improving?",
    choices: ["Blood pressure stabilizes and urine output improves", "Heart rate increases further", "Mucous membranes become drier", "Urine output decreases"],
    answer: "Blood pressure stabilizes and urine output improves",
    rationale: "Improved blood pressure, heart rate, urine output, and mucous membranes suggest improved fluid volume."
  },
  {
    id: "IVF-011",
    caseId: "IVF-CASE-006",
    patient: "Ms. Karen Moore",
    topic: "IV Fluids",
    subtopic: "IV Site Assessment",
    style: "Safety",
    difficulty: "Basic",
    question: "Ms. Moore's IV site is cool, swollen, and painful. What complication is most likely?",
    choices: ["Infiltration", "Expected finding", "Hyperkalemia", "Pulmonary embolism"],
    answer: "Infiltration",
    rationale: "Coolness, swelling, pain, and slowed infusion may indicate IV infiltration."
  },
  {
    id: "IVF-012",
    caseId: "IVF-CASE-006",
    patient: "Ms. Karen Moore",
    topic: "IV Fluids",
    subtopic: "IV Infiltration",
    style: "Take Action",
    difficulty: "Basic",
    question: "What should the nurse do first for Ms. Moore's suspected IV infiltration?",
    choices: ["Stop the infusion and assess the site", "Increase the flow rate", "Ignore the swelling", "Flush forcefully"],
    answer: "Stop the infusion and assess the site",
    rationale: "The infusion should be stopped when infiltration is suspected to prevent further tissue injury."
  },
  {
    id: "IVF-013",
    caseId: "IVF-CASE-007",
    patient: "Mr. Robert Lane",
    topic: "IV Fluids",
    subtopic: "Phlebitis",
    style: "Recognition",
    difficulty: "ATI",
    question: "Mr. Lane's IV site is red, warm, tender, and has a palpable cord. Which complication is most likely?",
    choices: ["Phlebitis", "Infiltration", "Hypoxia", "Hyponatremia"],
    answer: "Phlebitis",
    rationale: "Redness, warmth, tenderness, and a palpable cord along the vein suggest phlebitis."
  },
  {
    id: "IVF-014",
    caseId: "IVF-CASE-008",
    patient: "Ms. Patricia Young",
    topic: "IV Fluids",
    subtopic: "SATA",
    style: "SATA",
    difficulty: "ATI",
    question: "Which findings may indicate fluid volume excess? Select all that apply.",
    choices: ["Crackles", "Edema", "Bounding pulses", "Shortness of breath", "Dry mucous membranes"],
    answer: ["Crackles", "Edema", "Bounding pulses", "Shortness of breath"],
    rationale: "Fluid volume excess may cause crackles, edema, bounding pulses, dyspnea, weight gain, and increased blood pressure."
  },
  {
    id: "IVF-015",
    caseId: "IVF-CASE-009",
    patient: "Mr. William Carter",
    topic: "IV Fluids",
    subtopic: "SATA",
    style: "SATA",
    difficulty: "ATI",
    question: "Which findings may indicate fluid volume deficit? Select all that apply.",
    choices: ["Dry mucous membranes", "Poor skin turgor", "Tachycardia", "Hypotension", "Crackles"],
    answer: ["Dry mucous membranes", "Poor skin turgor", "Tachycardia", "Hypotension"],
    rationale: "Fluid volume deficit may cause dry mucous membranes, poor skin turgor, tachycardia, hypotension, thirst, and decreased urine output."
  }
];