const questionBank = [
  // Acid-Base
  ...fundamentalsQuestions,
  ...abgInterpretationQuestions,
  ...respiratoryAcidosisQuestions,
  ...respiratoryAlkalosisQuestions,
  ...metabolicAcidosisQuestions,
  ...metabolicAlkalosisQuestions,
  ...compensationQuestions,

  // Oxygenation
  ...oxygenDeliveryQuestions,
  ...hypoxiaQuestions,
  ...copdQuestions,
  ...asthmaQuestions,
  ...pneumoniaQuestions,
  ...chestTubeQuestions,
  ...pulmonaryEmbolismQuestions,
  ...tracheostomyQuestions,
  ...mechanicalVentilationQuestions,
  ...respiratoryFailureQuestions,
  ...airwayClearanceQuestions,
  ...oxygenationNursingManagementQuestions,
  ...oxygenationMixedReviewQuestions,

  // Fluids and Electrolytes
  ...sodiumDisorderQuestions,
  ...potassiumDisorderQuestions,
  ...calciumDisorderQuestions,
  ...magnesiumDisorderQuestions,
  ...ivFluidQuestions,
  ...fluidVolumeDeficitQuestions,
  ...fluidVolumeExcessQuestions,
  ...fluidsMixedReviewQuestions,

  // Neurology
  ...parkinsonsDiseaseQuestions,
  ...seizureQuestions,
  ...multipleSclerosisQuestions,
  ...neuroMixedReviewQuestions,
  ...neuroNursingManagementQuestions,
  ...neuroPriorityApplicationQuestions,
  ...neuroExamFocusQuestions,
  ...neuroSafetyReviewQuestions,
  ...neuroMedicationsReviewQuestions,
  ...neuroScenarioChallengeQuestions,
  ...neuroRapidReviewQuestions,

// Musculoskeletal
...boneFundamentalsQuestions,
...fractureTypesQuestions,
...fractureManagementQuestions,
...tractionQuestions,
...fractureComplicationsQuestions,
...neurovascularAssessmentQuestions,
...osteomyelitisQuestions,
...musculoskeletalMedicationQuestions,
...mobilityAssistiveDeviceQuestions,
...musculoskeletalPrioritySataQuestions,
...musculoskeletalMixedReviewQuestions,
...musculoskeletalNgnCaseQuestions,

// Perfusion
...perfusionFundamentalsQuestions,
...hypertensionQuestions,
...antihypertensiveMedicationQuestions,
...hypertensiveCrisisQuestions,
...peripheralArterialDiseaseQuestions,
...acuteArterialOcclusionQuestions,
...buergerRaynaudQuestions,
...dvtVteQuestions,
...anticoagulantQuestions,
...venousInsufficiencyQuestions,
...vascularUlcerQuestions,
...perfusionPrioritySataQuestions,
...ngnPerfusionCaseQuestions,
...perfusionMixedReviewQuestions,

// INFLAMMATION & INFECTION
...inflammationFundamentalsQuestions,
  ...appendicitisQuestions,
  ...celiacDiseaseQuestions,
  ...cholecystitisQuestions,
  ...pancreatitisQuestions,
  ...cirrhosisQuestions,
  ...hepatitisQuestions,
  ...inflammatoryBowelDiseaseQuestions,
  ...ostomyCareQuestions,
  ...infectionFundamentalsQuestions,
  ...pediatricInfectionsQuestions,
  ...respiratoryInfectionsQuestions,
  ...tuberculosisQuestions,
  ...urinaryTractInfectionQuestions,
  ...skinSoftTissueInfectionsQuestions,
  ...otitisMediaQuestions,
  ...conjunctivitisQuestions,
  ...ngnInflammationInfectionCaseQuestions
];

console.log(`NurseCase loaded ${questionBank.length} questions.`);