const parkinsonsDiseaseQuestions = [
  {
    id: "PD-001",
    caseId: "PD-CASE-001",
    patient: "Mr. James Allen",
    topic: "Parkinson's Disease",
    subtopic: "Clinical Manifestations",
    style: "Recognition",
    difficulty: "ATI",
    question: "Mr. Allen has a shuffling gait, resting hand tremor, slow movements, and a flat facial expression. Which condition is most likely?",
    choices: ["Parkinson's disease", "Multiple sclerosis", "Seizure disorder", "Myasthenia gravis"],
    answer: "Parkinson's disease",
    rationale: "Parkinson's disease commonly causes resting tremor, bradykinesia, rigidity, shuffling gait, and masked facial expression."
  },
  {
    id: "PD-002",
    caseId: "PD-CASE-001",
    patient: "Mr. James Allen",
    topic: "Parkinson's Disease",
    subtopic: "Priority Safety",
    style: "Priority",
    difficulty: "ATI",
    question: "Mr. Allen has a shuffling gait and difficulty starting movement. What is the nurse's priority concern?",
    choices: ["Fall risk", "Hyperglycemia", "Fluid overload", "Seizure aura"],
    answer: "Fall risk",
    rationale: "Parkinson's disease affects movement, balance, and gait, increasing fall risk."
  },
  {
    id: "PD-003",
    caseId: "PD-CASE-002",
    patient: "Ms. Carol Reed",
    topic: "Parkinson's Disease",
    subtopic: "Medication Timing",
    style: "Safety",
    difficulty: "ATI",
    question: "Ms. Reed takes carbidopa-levodopa for Parkinson's disease. Which nursing action is most important?",
    choices: ["Give the medication on time", "Hold medication when symptoms improve", "Crush all extended-release doses", "Give only at bedtime"],
    answer: "Give the medication on time",
    rationale: "Carbidopa-levodopa should be given on schedule to prevent worsening mobility and symptom fluctuations."
  },
  {
    id: "PD-004",
    caseId: "PD-CASE-002",
    patient: "Ms. Carol Reed",
    topic: "Parkinson's Disease",
    subtopic: "Medication Effects",
    style: "Evaluation",
    difficulty: "ATI",
    question: "Which finding indicates carbidopa-levodopa is effective?",
    choices: ["Improved movement and less rigidity", "Increased shuffling", "Worsening tremors", "New difficulty swallowing"],
    answer: "Improved movement and less rigidity",
    rationale: "Carbidopa-levodopa improves dopamine availability, which can decrease rigidity and improve movement."
  },
  {
    id: "PD-005",
    caseId: "PD-CASE-003",
    patient: "Mr. Robert King",
    topic: "Parkinson's Disease",
    subtopic: "Swallowing",
    style: "Priority",
    difficulty: "ATI",
    question: "Mr. King coughs while eating and has drooling related to Parkinson's disease. What is the priority nursing concern?",
    choices: ["Aspiration", "Hypernatremia", "Hypoglycemia", "Skin dryness"],
    answer: "Aspiration",
    rationale: "Parkinson's disease can impair swallowing and increase aspiration risk."
  },
  {
    id: "PD-006",
    caseId: "PD-CASE-003",
    patient: "Mr. Robert King",
    topic: "Parkinson's Disease",
    subtopic: "Aspiration Prevention",
    style: "Take Action",
    difficulty: "ATI",
    question: "Which intervention helps reduce aspiration risk for Mr. King?",
    choices: ["Place upright during meals", "Give thin liquids rapidly", "Feed while lying flat", "Avoid swallowing assessment"],
    answer: "Place upright during meals",
    rationale: "Upright positioning during meals helps reduce aspiration risk."
  },
  {
    id: "PD-007",
    caseId: "PD-CASE-004",
    patient: "Ms. Linda Scott",
    topic: "Parkinson's Disease",
    subtopic: "Mobility",
    style: "Teaching",
    difficulty: "Basic",
    question: "Ms. Scott has freezing episodes while walking. Which instruction is most helpful?",
    choices: ["Use visual cues and take deliberate steps", "Rush quickly through doorways", "Walk in the dark", "Avoid assistive devices"],
    answer: "Use visual cues and take deliberate steps",
    rationale: "Visual cues, deliberate stepping, and assistive devices can help patients manage freezing and gait instability."
  },
  {
    id: "PD-008",
    caseId: "PD-CASE-004",
    patient: "Ms. Linda Scott",
    topic: "Parkinson's Disease",
    subtopic: "Home Safety",
    style: "Safety",
    difficulty: "ATI",
    question: "Which home safety instruction is most appropriate for Ms. Scott?",
    choices: ["Remove throw rugs and clutter", "Use slippery socks", "Keep pathways dimly lit", "Avoid grab bars"],
    answer: "Remove throw rugs and clutter",
    rationale: "Removing tripping hazards helps reduce fall risk."
  },
  {
    id: "PD-009",
    caseId: "PD-CASE-005",
    patient: "Mr. Henry Moore",
    topic: "Parkinson's Disease",
    subtopic: "Autonomic Symptoms",
    style: "Analyze Cues",
    difficulty: "ATI",
    question: "Mr. Moore has Parkinson's disease and reports constipation. How should the nurse interpret this?",
    choices: ["It can occur due to slowed GI motility", "It means the disease is cured", "It is unrelated to Parkinson's disease", "It always indicates bowel obstruction"],
    answer: "It can occur due to slowed GI motility",
    rationale: "Parkinson's disease can affect autonomic function and movement, contributing to constipation."
  },
  {
    id: "PD-010",
    caseId: "PD-CASE-005",
    patient: "Mr. Henry Moore",
    topic: "Parkinson's Disease",
    subtopic: "Constipation",
    style: "Teaching",
    difficulty: "Basic",
    question: "Which teaching can help manage constipation in Parkinson's disease?",
    choices: ["Increase fluids, fiber, and activity as tolerated", "Avoid fluids", "Stay immobile", "Use only low-fiber foods"],
    answer: "Increase fluids, fiber, and activity as tolerated",
    rationale: "Fluids, fiber, and activity can help improve bowel motility."
  },
  {
    id: "PD-011",
    caseId: "PD-CASE-006",
    patient: "Ms. Angela Hill",
    topic: "Parkinson's Disease",
    subtopic: "Communication",
    style: "Application",
    difficulty: "ATI",
    question: "Ms. Hill speaks softly and slowly due to Parkinson's disease. Which nursing action is best?",
    choices: ["Allow extra time for communication", "Rush her responses", "Speak over her", "Assume she is confused"],
    answer: "Allow extra time for communication",
    rationale: "Bradykinesia and speech changes may slow communication. The nurse should allow time and support communication."
  },
  {
    id: "PD-012",
    caseId: "PD-CASE-006",
    patient: "Ms. Angela Hill",
    topic: "Parkinson's Disease",
    subtopic: "Psychosocial",
    style: "Analyze Cues",
    difficulty: "ATI",
    question: "Ms. Hill says she avoids social events because of tremors and speech changes. What is the nurse's best response?",
    choices: ["Assess coping and support resources", "Tell her not to worry", "Avoid discussing emotions", "Document only"],
    answer: "Assess coping and support resources",
    rationale: "Chronic neurologic disease can affect emotional health and social interaction. Psychosocial support is important."
  },
  {
    id: "PD-013",
    caseId: "PD-CASE-007",
    patient: "Mr. David Young",
    topic: "Parkinson's Disease",
    subtopic: "Priority",
    style: "Priority",
    difficulty: "ATI",
    question: "Which finding in a patient with Parkinson's disease requires immediate follow-up?",
    choices: ["Choking during meals", "Resting tremor", "Masked face", "Slow movement"],
    answer: "Choking during meals",
    rationale: "Choking suggests impaired swallowing and aspiration risk, which is the priority."
  },
  {
    id: "PD-014",
    caseId: "PD-CASE-008",
    patient: "Ms. Nora Lane",
    topic: "Parkinson's Disease",
    subtopic: "SATA",
    style: "SATA",
    difficulty: "ATI",
    question: "Which findings are commonly associated with Parkinson's disease? Select all that apply.",
    choices: ["Resting tremor", "Bradykinesia", "Rigidity", "Shuffling gait", "Sudden loss of consciousness"],
    answer: ["Resting tremor", "Bradykinesia", "Rigidity", "Shuffling gait"],
    rationale: "Parkinson's disease commonly causes resting tremor, bradykinesia, rigidity, postural instability, and shuffling gait."
  },
  {
    id: "PD-015",
    caseId: "PD-CASE-009",
    patient: "Mr. Paul Grant",
    topic: "Parkinson's Disease",
    subtopic: "Evaluation",
    style: "Evaluation",
    difficulty: "ATI",
    question: "Which outcome shows the nursing plan for Parkinson's disease is effective?",
    choices: ["Patient ambulates safely with assistive device", "Patient has repeated falls", "Patient coughs with every meal", "Patient stops all medications"],
    answer: "Patient ambulates safely with assistive device",
    rationale: "Safe mobility shows improved fall prevention and functional support."
  }
];