const seizureQuestions = [
  {
    id: "SZ-001",
    caseId: "SZ-CASE-001",
    patient: "Ms. Taylor Brown",
    topic: "Seizures",
    subtopic: "Recognition",
    style: "Recognition",
    difficulty: "ATI",
    question: "Ms. Brown suddenly loses consciousness, has stiffening of the body, rhythmic jerking, and then becomes very tired afterward. Which type of event is most likely?",
    choices: ["Generalized tonic-clonic seizure", "Transient ischemic attack", "Parkinsonian tremor", "Multiple sclerosis relapse"],
    answer: "Generalized tonic-clonic seizure",
    rationale: "A tonic-clonic seizure involves loss of consciousness, stiffening, rhythmic jerking, and a postictal period."
  },
  {
    id: "SZ-002",
    caseId: "SZ-CASE-001",
    patient: "Ms. Taylor Brown",
    topic: "Seizures",
    subtopic: "Priority",
    style: "Priority",
    difficulty: "ATI",
    question: "Ms. Brown begins having a tonic-clonic seizure in bed. What should the nurse do first?",
    choices: ["Protect her from injury and turn her to the side if possible", "Place an object in her mouth", "Restrain all extremities", "Give oral fluids"],
    answer: "Protect her from injury and turn her to the side if possible",
    rationale: "During a seizure, protect the patient from injury, maintain airway safety, and position on the side if possible. Do not restrain or place anything in the mouth."
  },
  {
    id: "SZ-003",
    caseId: "SZ-CASE-002",
    patient: "Mr. Henry Scott",
    topic: "Seizures",
    subtopic: "Safety",
    style: "Safety",
    difficulty: "ATI",
    question: "Mr. Scott is at risk for seizures. Which intervention is appropriate?",
    choices: ["Pad side rails and keep suction available", "Keep bed in highest position", "Leave clutter around the bed", "Restrict all observation"],
    answer: "Pad side rails and keep suction available",
    rationale: "Seizure precautions include padded rails, bed in low position, oxygen and suction available, and maintaining a safe environment."
  },
  {
    id: "SZ-004",
    caseId: "SZ-CASE-002",
    patient: "Mr. Henry Scott",
    topic: "Seizures",
    subtopic: "What Not To Do",
    style: "Safety",
    difficulty: "ATI",
    question: "Which action should the nurse avoid during Mr. Scott's seizure?",
    choices: ["Putting anything in his mouth", "Turning him to the side", "Protecting his head", "Timing the seizure"],
    answer: "Putting anything in his mouth",
    rationale: "Nothing should be placed in the patient's mouth during a seizure because it can cause injury or airway obstruction."
  },
  {
    id: "SZ-005",
    caseId: "SZ-CASE-003",
    patient: "Ms. Olivia Grant",
    topic: "Seizures",
    subtopic: "Postictal Period",
    style: "Recognition",
    difficulty: "ATI",
    question: "After a seizure, Ms. Grant is confused, sleepy, and has a headache. How should the nurse interpret this?",
    choices: ["Expected postictal findings", "Signs that the seizure did not occur", "A Parkinson's symptom", "A normal finding unrelated to seizures"],
    answer: "Expected postictal findings",
    rationale: "The postictal period may include confusion, sleepiness, headache, and fatigue after a seizure."
  },
  {
    id: "SZ-006",
    caseId: "SZ-CASE-003",
    patient: "Ms. Olivia Grant",
    topic: "Seizures",
    subtopic: "Postictal Care",
    style: "Take Action",
    difficulty: "ATI",
    question: "What should the nurse do during the postictal period?",
    choices: ["Maintain airway and allow rest while monitoring", "Force the patient to ambulate immediately", "Give oral fluids before fully alert", "Leave the patient unattended"],
    answer: "Maintain airway and allow rest while monitoring",
    rationale: "After a seizure, monitor airway, breathing, level of consciousness, injuries, and allow the patient to rest."
  },
  {
    id: "SZ-007",
    caseId: "SZ-CASE-004",
    patient: "Mr. David King",
    topic: "Seizures",
    subtopic: "Status Epilepticus",
    style: "Priority",
    difficulty: "ATI",
    question: "Mr. King has a seizure lasting longer than 5 minutes. Which complication is the nurse most concerned about?",
    choices: ["Status epilepticus", "Hypercalcemia", "Parkinsonian crisis", "Fluid volume excess"],
    answer: "Status epilepticus",
    rationale: "A seizure lasting longer than 5 minutes or repeated seizures without recovery can indicate status epilepticus, a medical emergency."
  },
  {
    id: "SZ-008",
    caseId: "SZ-CASE-004",
    patient: "Mr. David King",
    topic: "Seizures",
    subtopic: "Emergency Action",
    style: "Take Action",
    difficulty: "ATI",
    question: "Mr. King continues seizing after 5 minutes. What should the nurse do?",
    choices: ["Call for emergency assistance and prepare ordered rescue medication", "Leave the room", "Offer food", "Restrain him tightly"],
    answer: "Call for emergency assistance and prepare ordered rescue medication",
    rationale: "Status epilepticus requires rapid intervention to protect the airway, support breathing, and stop seizure activity."
  },
  {
    id: "SZ-009",
    caseId: "SZ-CASE-005",
    patient: "Ms. Angela Reed",
    topic: "Seizures",
    subtopic: "Medication Teaching",
    style: "Teaching",
    difficulty: "ATI",
    question: "Ms. Reed is prescribed antiseizure medication. Which teaching is most important?",
    choices: ["Take the medication consistently as prescribed", "Stop medication once seizures improve", "Double doses after missed doses without asking", "Take only when a seizure starts"],
    answer: "Take the medication consistently as prescribed",
    rationale: "Antiseizure medications must be taken consistently to maintain therapeutic levels and reduce seizure risk."
  },
  {
    id: "SZ-010",
    caseId: "SZ-CASE-005",
    patient: "Ms. Angela Reed",
    topic: "Seizures",
    subtopic: "Medication Safety",
    style: "Safety",
    difficulty: "ATI",
    question: "Which statement by Ms. Reed requires correction?",
    choices: ["I can stop my seizure medication when I feel better", "I should take my medication as prescribed", "I should report side effects", "I should avoid missed doses"],
    answer: "I can stop my seizure medication when I feel better",
    rationale: "Stopping antiseizure medication suddenly can trigger seizures or status epilepticus."
  },
  {
    id: "SZ-011",
    caseId: "SZ-CASE-006",
    patient: "Mr. Paul Young",
    topic: "Seizures",
    subtopic: "Triggers",
    style: "Teaching",
    difficulty: "Basic",
    question: "Mr. Young asks what can trigger seizures. Which factor should the nurse include?",
    choices: ["Sleep deprivation", "Consistent medication use", "Regular meals", "Adequate rest"],
    answer: "Sleep deprivation",
    rationale: "Common seizure triggers can include missed medications, sleep deprivation, alcohol use, illness, stress, and flashing lights in some patients."
  },
  {
    id: "SZ-012",
    caseId: "SZ-CASE-006",
    patient: "Mr. Paul Young",
    topic: "Seizures",
    subtopic: "Lifestyle Safety",
    style: "Safety",
    difficulty: "ATI",
    question: "Which safety teaching is appropriate for Mr. Young with seizure disorder?",
    choices: ["Avoid swimming alone", "Drive without restrictions immediately", "Climb ladders alone", "Take baths alone with locked door"],
    answer: "Avoid swimming alone",
    rationale: "Patients with seizures should avoid high-risk activities alone, such as swimming, bathing, heights, and operating dangerous equipment."
  },
  {
    id: "SZ-013",
    caseId: "SZ-CASE-007",
    patient: "Ms. Nora Lane",
    topic: "Seizures",
    subtopic: "Absence Seizure",
    style: "Recognition",
    difficulty: "ATI",
    question: "Ms. Lane's child has brief staring spells and then resumes activity without confusion. Which seizure type is most likely?",
    choices: ["Absence seizure", "Tonic-clonic seizure", "Status epilepticus", "Parkinsonian tremor"],
    answer: "Absence seizure",
    rationale: "Absence seizures are brief episodes of staring or impaired awareness, often without a postictal period."
  },
  {
    id: "SZ-014",
    caseId: "SZ-CASE-008",
    patient: "Mr. Ryan Hall",
    topic: "Seizures",
    subtopic: "Documentation",
    style: "Application",
    difficulty: "ATI",
    question: "After Mr. Hall has a seizure, which information should the nurse document?",
    choices: ["Time started, duration, movements, airway status, and postictal behavior", "Only the room number", "Only that it happened", "Meal preference"],
    answer: "Time started, duration, movements, airway status, and postictal behavior",
    rationale: "Seizure documentation should include onset, duration, type of movements, level of consciousness, airway/oxygenation, injuries, and postictal state."
  },
  {
    id: "SZ-015",
    caseId: "SZ-CASE-009",
    patient: "Ms. Hannah Cole",
    topic: "Seizures",
    subtopic: "SATA",
    style: "SATA",
    difficulty: "ATI",
    question: "Which actions are appropriate during a seizure? Select all that apply.",
    choices: ["Protect the head", "Time the seizure", "Turn patient to side if possible", "Place object in mouth", "Loosen restrictive clothing"],
    answer: ["Protect the head", "Time the seizure", "Turn patient to side if possible", "Loosen restrictive clothing"],
    rationale: "During a seizure, protect from injury, time the seizure, maintain airway safety, turn to side if possible, and loosen restrictive clothing. Do not place anything in the mouth."
  }
];