const asthmaQuestions = [
  {
    id: "ASTH-001",
    caseId: "ASTH-CASE-001",
    patient: "Olivia Harris",
    topic: "Asthma",
    subtopic: "Asthma Exacerbation",
    style: "Recognition",
    difficulty: "ATI",
    question: "Olivia arrives with wheezing, chest tightness, shortness of breath, and difficulty speaking in full sentences. Which condition is most likely?",
    choices: ["Asthma exacerbation", "Metabolic alkalosis", "Hypercalcemia", "Fluid volume excess"],
    answer: "Asthma exacerbation",
    rationale: "Wheezing, chest tightness, shortness of breath, and difficulty speaking are classic signs of an asthma exacerbation."
  },
  {
    id: "ASTH-002",
    caseId: "ASTH-CASE-001",
    patient: "Olivia Harris",
    topic: "Asthma",
    subtopic: "Priority",
    style: "Priority",
    difficulty: "ATI",
    question: "Olivia is wheezing and using accessory muscles. What is the nurse's priority?",
    choices: ["Assess airway and breathing", "Offer food", "Teach discharge instructions first", "Ask about bowel habits"],
    answer: "Assess airway and breathing",
    rationale: "Asthma affects airway and breathing. Respiratory assessment and oxygenation are the priority."
  },
  {
    id: "ASTH-003",
    caseId: "ASTH-CASE-001",
    patient: "Olivia Harris",
    topic: "Asthma",
    subtopic: "Medication",
    style: "Take Action",
    difficulty: "ATI",
    question: "Which medication should the nurse anticipate first for acute wheezing and bronchospasm?",
    choices: ["Short-acting beta-2 agonist", "Oral calcium", "Antacid", "Potassium chloride"],
    answer: "Short-acting beta-2 agonist",
    rationale: "A short-acting beta-2 agonist is a rescue medication used for rapid bronchodilation during acute asthma symptoms."
  },
  {
    id: "ASTH-004",
    caseId: "ASTH-CASE-002",
    patient: "Marcus Reed",
    topic: "Asthma",
    subtopic: "Severe Asthma",
    style: "Safety",
    difficulty: "ATI",
    question: "Marcus has asthma. He suddenly has minimal wheezing, severe respiratory distress, and very little air movement. Which finding is most concerning?",
    choices: ["Silent chest", "Mild expiratory wheeze", "Occasional dry cough", "Speaking in full sentences"],
    answer: "Silent chest",
    rationale: "A silent chest can mean little to no air movement and is a life-threatening sign of severe airway obstruction."
  },
  {
    id: "ASTH-005",
    caseId: "ASTH-CASE-002",
    patient: "Marcus Reed",
    topic: "Asthma",
    subtopic: "Escalation",
    style: "Priority",
    difficulty: "ATI",
    question: "Marcus is unable to speak, has SpO₂ 84%, and has decreased breath sounds. What should the nurse do?",
    choices: ["Stay with the patient, apply oxygen as prescribed, and call for rapid assistance", "Leave him alone to rest", "Give oral fluids first", "Delay care until rounds"],
    answer: "Stay with the patient, apply oxygen as prescribed, and call for rapid assistance",
    rationale: "Severe asthma with hypoxia and decreased air movement requires immediate intervention and escalation of care."
  },
  {
    id: "ASTH-006",
    caseId: "ASTH-CASE-003",
    patient: "Jasmine Cole",
    topic: "Asthma",
    subtopic: "Rescue Inhaler Teaching",
    style: "Teaching",
    difficulty: "Basic",
    question: "Jasmine asks when to use her rescue inhaler. Which response is best?",
    choices: ["Use it for sudden wheezing or shortness of breath", "Use it only once per year", "Use it instead of all controller medications", "Use it only after symptoms are severe for several hours"],
    answer: "Use it for sudden wheezing or shortness of breath",
    rationale: "A rescue inhaler is used for quick relief of acute bronchospasm."
  },
  {
    id: "ASTH-007",
    caseId: "ASTH-CASE-003",
    patient: "Jasmine Cole",
    topic: "Asthma",
    subtopic: "Controller Medication",
    style: "Teaching",
    difficulty: "ATI",
    question: "Jasmine is prescribed an inhaled corticosteroid. Which teaching is most important?",
    choices: ["Rinse your mouth after use", "Use it only during severe attacks", "Stop it once breathing improves", "Use it as a replacement for emergency care"],
    answer: "Rinse your mouth after use",
    rationale: "Inhaled corticosteroids can increase risk for oral candidiasis. Rinsing the mouth after use reduces this risk."
  },
  {
    id: "ASTH-008",
    caseId: "ASTH-CASE-004",
    patient: "Ethan Moore",
    topic: "Asthma",
    subtopic: "Medication Evaluation",
    style: "Evaluation",
    difficulty: "ATI",
    question: "Ethan receives a bronchodilator for wheezing. Which finding indicates the medication was effective?",
    choices: ["Decreased wheezing and easier breathing", "Worsening retractions", "SpO₂ decreases", "Unable to speak"],
    answer: "Decreased wheezing and easier breathing",
    rationale: "Improved airflow is shown by decreased wheezing, easier breathing, and improved oxygen saturation."
  },
  {
    id: "ASTH-009",
    caseId: "ASTH-CASE-004",
    patient: "Ethan Moore",
    topic: "Asthma",
    subtopic: "Medication Side Effects",
    style: "Analyze Cues",
    difficulty: "ATI",
    question: "After using albuterol, Ethan reports feeling shaky and his heart rate is 118/min. How should the nurse interpret this?",
    choices: ["Expected side effect of a beta-2 agonist", "Severe hypocalcemia", "Metabolic acidosis", "Normal finding unrelated to medication"],
    answer: "Expected side effect of a beta-2 agonist",
    rationale: "Short-acting beta-2 agonists can cause tremors, nervousness, and tachycardia."
  },
  {
    id: "ASTH-010",
    caseId: "ASTH-CASE-005",
    patient: "Maya Phillips",
    topic: "Asthma",
    subtopic: "Trigger Management",
    style: "Teaching",
    difficulty: "Basic",
    question: "Maya has asthma triggered by dust and smoke. Which teaching is most appropriate?",
    choices: ["Avoid known triggers when possible", "Smoke exposure helps strengthen the lungs", "Stop all medications when triggers are avoided", "Only treat asthma after hospitalization"],
    answer: "Avoid known triggers when possible",
    rationale: "Avoiding triggers can reduce asthma exacerbations."
  },
  {
    id: "ASTH-011",
    caseId: "ASTH-CASE-005",
    patient: "Maya Phillips",
    topic: "Asthma",
    subtopic: "Environmental Safety",
    style: "Safety",
    difficulty: "ATI",
    question: "Which statement by Maya requires correction?",
    choices: ["I can keep smoking in the home as long as windows are open", "I should avoid smoke exposure", "I should identify my asthma triggers", "I should follow my asthma action plan"],
    answer: "I can keep smoking in the home as long as windows are open",
    rationale: "Smoke is a common asthma trigger. Opening windows does not eliminate risk."
  },
  {
    id: "ASTH-012",
    caseId: "ASTH-CASE-006",
    patient: "Noah Bennett",
    topic: "Asthma",
    subtopic: "Priority Assessment",
    style: "Priority",
    difficulty: "ATI",
    question: "Noah has asthma and reports worsening shortness of breath. Which assessment is most important?",
    choices: ["Lung sounds, work of breathing, SpO₂, and ability to speak", "Hair texture", "Last meal", "Family history only"],
    answer: "Lung sounds, work of breathing, SpO₂, and ability to speak",
    rationale: "These findings help determine severity of respiratory distress and need for urgent intervention."
  },
  {
    id: "ASTH-013",
    caseId: "ASTH-CASE-006",
    patient: "Noah Bennett",
    topic: "Asthma",
    subtopic: "Clinical Judgment",
    style: "Analyze Cues",
    difficulty: "ATI",
    question: "Which finding suggests Noah's asthma is worsening?",
    choices: ["Difficulty speaking in full sentences", "Improved air movement", "Decreased respiratory rate with comfort", "SpO₂ improves to 97%"],
    answer: "Difficulty speaking in full sentences",
    rationale: "Inability to speak full sentences suggests significant respiratory distress."
  },
  {
    id: "ASTH-014",
    caseId: "ASTH-CASE-007",
    patient: "Arianna Smith",
    topic: "Asthma",
    subtopic: "Peak Flow",
    style: "Application",
    difficulty: "ATI",
    question: "Arianna uses a peak flow meter at home. Her reading is much lower than her personal best and she is wheezing. What should she do?",
    choices: ["Follow her asthma action plan", "Ignore the reading", "Stop all inhalers", "Wait one week before acting"],
    answer: "Follow her asthma action plan",
    rationale: "A drop in peak flow with symptoms indicates worsening airflow and should be managed according to the asthma action plan."
  },
  {
    id: "ASTH-015",
    caseId: "ASTH-CASE-007",
    patient: "Arianna Smith",
    topic: "Asthma",
    subtopic: "Evaluation",
    style: "Evaluation",
    difficulty: "ATI",
    question: "Which finding suggests Arianna's asthma control is improving?",
    choices: ["Fewer nighttime symptoms", "More frequent rescue inhaler use", "Increasing wheezing", "Decreasing activity tolerance"],
    answer: "Fewer nighttime symptoms",
    rationale: "Good asthma control includes fewer symptoms, less rescue inhaler use, and better activity tolerance."
  },
  {
    id: "ASTH-016",
    caseId: "ASTH-CASE-008",
    patient: "Mr. Walter Gray",
    topic: "Asthma",
    subtopic: "Older Adult",
    style: "Priority",
    difficulty: "ATI",
    question: "Mr. Gray has asthma and a history of heart disease. After repeated albuterol treatments, he reports palpitations. What should the nurse do?",
    choices: ["Assess heart rate and rhythm", "Ignore the report", "Give more doses rapidly without assessment", "Tell him palpitations are impossible"],
    answer: "Assess heart rate and rhythm",
    rationale: "Beta-2 agonists can cause tachycardia and palpitations. Cardiac assessment is important, especially with heart disease."
  },
  {
    id: "ASTH-017",
    caseId: "ASTH-CASE-008",
    patient: "Mr. Walter Gray",
    topic: "Asthma",
    subtopic: "Safety",
    style: "Safety",
    difficulty: "ATI",
    question: "Which finding after asthma treatment should be reported promptly?",
    choices: ["Chest pain and severe tachycardia", "Mild hand tremor", "Slight nervousness", "Improved wheezing"],
    answer: "Chest pain and severe tachycardia",
    rationale: "Chest pain and severe tachycardia may indicate a serious adverse response and require prompt follow-up."
  },
  {
    id: "ASTH-018",
    caseId: "ASTH-CASE-009",
    patient: "Lily Carter",
    topic: "Asthma",
    subtopic: "Pediatric Teaching",
    style: "Teaching",
    difficulty: "ATI",
    question: "Lily's parent asks how to help prevent asthma attacks. Which instruction is best?",
    choices: ["Use prescribed controller medications consistently and avoid triggers", "Stop controller medication when symptoms improve", "Allow exposure to smoke to build tolerance", "Use rescue medication as the only daily treatment"],
    answer: "Use prescribed controller medications consistently and avoid triggers",
    rationale: "Asthma prevention includes trigger control and consistent use of prescribed controller therapy."
  },
  {
    id: "ASTH-019",
    caseId: "ASTH-CASE-009",
    patient: "Lily Carter",
    topic: "Asthma",
    subtopic: "SATA",
    style: "SATA",
    difficulty: "ATI",
    question: "Which findings may indicate an asthma exacerbation? Select all that apply.",
    choices: ["Wheezing", "Chest tightness", "Shortness of breath", "Difficulty speaking", "Improved oxygen saturation"],
    answer: ["Wheezing", "Chest tightness", "Shortness of breath", "Difficulty speaking"],
    rationale: "Asthma exacerbation may cause wheezing, chest tightness, shortness of breath, cough, retractions, and difficulty speaking."
  },
  {
    id: "ASTH-020",
    caseId: "ASTH-CASE-010",
    patient: "Ms. Tasha Green",
    topic: "Asthma",
    subtopic: "Emergency",
    style: "Priority",
    difficulty: "ATI",
    question: "Ms. Green has severe asthma symptoms and her SpO₂ is 82%. She is anxious and unable to complete sentences. What is the nurse's priority?",
    choices: ["Support oxygenation and prepare for emergency treatment", "Complete discharge teaching", "Have her walk in the hall", "Give oral fluids only"],
    answer: "Support oxygenation and prepare for emergency treatment",
    rationale: "Severe hypoxemia and inability to speak indicate respiratory emergency. Oxygenation and rapid treatment are priority."
  }
];