const chestTubeQuestions = [
  {
    id: "CT-001",
    caseId: "CT-CASE-001",
    patient: "Jessica Moore",
    topic: "Chest Tubes",
    subtopic: "Pneumothorax",
    style: "Recognition",
    difficulty: "ATI",
    question: "Jessica has a chest tube after a pneumothorax. Which finding suggests the chest tube is helping?",
    choices: ["Improved breath sounds", "Tracheal deviation", "Worsening dyspnea", "Increasing cyanosis"],
    answer: "Improved breath sounds",
    rationale: "Improved breath sounds suggest lung re-expansion and improved ventilation."
  },
  {
    id: "CT-002",
    caseId: "CT-CASE-001",
    patient: "Jessica Moore",
    topic: "Chest Tubes",
    subtopic: "Disconnection",
    style: "Safety",
    difficulty: "ATI",
    question: "Jessica's chest tube disconnects from the drainage system. What should the nurse do first?",
    choices: ["Place the end of the tube in sterile water", "Clamp the tube for 30 minutes", "Pull the tube out", "Turn off suction permanently"],
    answer: "Place the end of the tube in sterile water",
    rationale: "Placing the tube end in sterile water creates a temporary water seal and helps prevent air from entering the pleural space."
  },
  {
    id: "CT-003",
    caseId: "CT-CASE-002",
    patient: "Mr. Ryan Hall",
    topic: "Chest Tubes",
    subtopic: "Tension Pneumothorax",
    style: "Recognition",
    difficulty: "ATI",
    question: "Mr. Hall has sudden respiratory distress, absent breath sounds on the right side, and tracheal deviation. Which complication is most likely?",
    choices: ["Tension pneumothorax", "Hypocalcemia", "Metabolic alkalosis", "Fluid volume deficit"],
    answer: "Tension pneumothorax",
    rationale: "Sudden respiratory distress, absent breath sounds, and tracheal deviation suggest tension pneumothorax, a life-threatening emergency."
  },
  {
    id: "CT-004",
    caseId: "CT-CASE-002",
    patient: "Mr. Ryan Hall",
    topic: "Chest Tubes",
    subtopic: "Priority",
    style: "Priority",
    difficulty: "ATI",
    question: "Mr. Hall develops signs of tension pneumothorax. What is the priority nursing action?",
    choices: ["Call for immediate help and support oxygenation", "Encourage oral fluids", "Place him flat", "Delay assessment until x-ray"],
    answer: "Call for immediate help and support oxygenation",
    rationale: "Tension pneumothorax can rapidly impair ventilation and circulation. The nurse should stay with the patient, support breathing, and get help immediately."
  },
  {
    id: "CT-005",
    caseId: "CT-CASE-003",
    patient: "Ms. Carla Evans",
    topic: "Chest Tubes",
    subtopic: "Drainage System",
    style: "Safety",
    difficulty: "ATI",
    question: "Where should the nurse keep the chest drainage system?",
    choices: ["Below chest level", "Above the patient's head", "On the bed beside the patient", "Clamped at all times"],
    answer: "Below chest level",
    rationale: "The drainage system should stay below chest level to promote drainage and prevent backflow."
  },
  {
    id: "CT-006",
    caseId: "CT-CASE-003",
    patient: "Ms. Carla Evans",
    topic: "Chest Tubes",
    subtopic: "Clamping",
    style: "Safety",
    difficulty: "ATI",
    question: "Which chest tube action should the nurse avoid unless specifically prescribed?",
    choices: ["Routinely clamping the chest tube", "Assessing breath sounds", "Monitoring drainage", "Keeping the system upright"],
    answer: "Routinely clamping the chest tube",
    rationale: "Routine clamping can cause pressure buildup and may lead to tension pneumothorax."
  },
  {
    id: "CT-007",
    caseId: "CT-CASE-004",
    patient: "Mr. Peter Young",
    topic: "Chest Tubes",
    subtopic: "Air Leak",
    style: "Analyze Cues",
    difficulty: "ATI",
    question: "Mr. Young's chest drainage system has continuous bubbling in the water seal chamber. What does this most likely indicate?",
    choices: ["Air leak", "Normal tidaling only", "Resolved pneumothorax", "Fluid overload"],
    answer: "Air leak",
    rationale: "Continuous bubbling in the water seal chamber may indicate an air leak in the system or from the patient."
  },
  {
    id: "CT-008",
    caseId: "CT-CASE-004",
    patient: "Mr. Peter Young",
    topic: "Chest Tubes",
    subtopic: "Tidaling",
    style: "Recognition",
    difficulty: "ATI",
    question: "The nurse observes gentle fluctuation in the water seal chamber with respirations. How should this be interpreted?",
    choices: ["Expected tidaling", "Immediate cardiac arrest", "A disconnected tube", "Need to clamp the tube"],
    answer: "Expected tidaling",
    rationale: "Gentle fluctuation, or tidaling, may be expected as pressure changes with breathing."
  },
  {
    id: "CT-009",
    caseId: "CT-CASE-005",
    patient: "Ms. Naomi Scott",
    topic: "Chest Tubes",
    subtopic: "Drainage",
    style: "Priority",
    difficulty: "ATI",
    question: "Ms. Scott's chest tube drainage suddenly increases to a large amount of bright red blood. What should the nurse do?",
    choices: ["Notify the provider immediately", "Document as expected only", "Strip the tubing aggressively", "Raise the system above chest level"],
    answer: "Notify the provider immediately",
    rationale: "A sudden large amount of bright red drainage may indicate bleeding and requires immediate provider notification."
  },
  {
    id: "CT-010",
    caseId: "CT-CASE-005",
    patient: "Ms. Naomi Scott",
    topic: "Chest Tubes",
    subtopic: "Assessment",
    style: "Analyze Cues",
    difficulty: "ATI",
    question: "Which assessment is most important for Ms. Scott with a chest tube?",
    choices: ["Respiratory status, breath sounds, drainage amount, and insertion site", "Hair texture", "Appetite only", "Vision test only"],
    answer: "Respiratory status, breath sounds, drainage amount, and insertion site",
    rationale: "Chest tube assessment focuses on breathing, lung sounds, drainage, tube patency, and insertion site integrity."
  },
  {
    id: "CT-011",
    caseId: "CT-CASE-006",
    patient: "Mr. Samuel King",
    topic: "Chest Tubes",
    subtopic: "Tube Removal",
    style: "Teaching",
    difficulty: "ATI",
    question: "Mr. King is scheduled for chest tube removal. Which instruction should the nurse anticipate giving during removal?",
    choices: ["Take a deep breath and bear down if instructed", "Cough continuously during removal", "Remove the dressing immediately after", "Hold your breath for 10 minutes"],
    answer: "Take a deep breath and bear down if instructed",
    rationale: "During chest tube removal, the patient may be instructed to perform the Valsalva maneuver or hold breath to reduce air entry."
  },
  {
    id: "CT-012",
    caseId: "CT-CASE-006",
    patient: "Mr. Samuel King",
    topic: "Chest Tubes",
    subtopic: "Post Removal",
    style: "Evaluation",
    difficulty: "ATI",
    question: "After chest tube removal, which finding requires immediate follow-up?",
    choices: ["Sudden shortness of breath", "Clean dry dressing", "Mild soreness", "Stable vital signs"],
    answer: "Sudden shortness of breath",
    rationale: "Sudden dyspnea after chest tube removal may indicate recurrence of pneumothorax."
  },
  {
    id: "CT-013",
    caseId: "CT-CASE-007",
    patient: "Ms. Lily Morris",
    topic: "Chest Tubes",
    subtopic: "Accidental Removal",
    style: "Safety",
    difficulty: "ATI",
    question: "Ms. Morris accidentally pulls out her chest tube. What should the nurse do first?",
    choices: ["Apply a sterile occlusive dressing", "Leave the site open to air", "Insert the tube back in", "Clamp the removed tube"],
    answer: "Apply a sterile occlusive dressing",
    rationale: "If a chest tube is accidentally removed, the nurse should cover the site with a sterile occlusive dressing and notify the provider."
  },
  {
    id: "CT-014",
    caseId: "CT-CASE-007",
    patient: "Ms. Lily Morris",
    topic: "Chest Tubes",
    subtopic: "Emergency",
    style: "Priority",
    difficulty: "ATI",
    question: "After accidental chest tube removal, which assessment is most important?",
    choices: ["Respiratory status", "Appetite", "Bowel sounds only", "Urine color"],
    answer: "Respiratory status",
    rationale: "The patient is at risk for pneumothorax or respiratory compromise. Respiratory assessment is priority."
  },
  {
    id: "CT-015",
    caseId: "CT-CASE-008",
    patient: "Mr. Eric Turner",
    topic: "Chest Tubes",
    subtopic: "SATA",
    style: "SATA",
    difficulty: "ATI",
    question: "Which nursing actions are appropriate for a patient with a chest tube? Select all that apply.",
    choices: ["Keep drainage system below chest level", "Assess breath sounds", "Monitor drainage amount", "Routinely clamp the tube", "Ensure connections are secure"],
    answer: ["Keep drainage system below chest level", "Assess breath sounds", "Monitor drainage amount", "Ensure connections are secure"],
    rationale: "Appropriate care includes keeping the system below chest level, assessing respiratory status, monitoring drainage, and securing connections. Routine clamping is unsafe."
  }
];