const copdQuestions = [
  {
    id: "COPD-001",
    caseId: "COPD-CASE-001",
    patient: "Mr. David Lewis",
    topic: "COPD",
    subtopic: "COPD Exacerbation",
    style: "Recognition",
    difficulty: "ATI",
    question: "Mr. Lewis has COPD and arrives with dyspnea, wheezing, use of accessory muscles, and SpO₂ 88%. Which problem is most likely?",
    choices: ["Impaired gas exchange", "Hypercalcemia", "Fluid volume deficit only", "Metabolic alkalosis"],
    answer: "Impaired gas exchange",
    rationale: "COPD causes airflow limitation and impaired gas exchange, leading to dyspnea, low oxygen saturation, wheezing, and increased work of breathing."
  },
  {
    id: "COPD-002",
    caseId: "COPD-CASE-001",
    patient: "Mr. David Lewis",
    topic: "COPD",
    subtopic: "Priority",
    style: "Priority",
    difficulty: "ATI",
    question: "Mr. Lewis is short of breath and using accessory muscles. What should the nurse do first?",
    choices: ["Place him in high Fowler's position", "Lay him flat", "Encourage sleep", "Restrict all fluids"],
    answer: "Place him in high Fowler's position",
    rationale: "High Fowler's promotes lung expansion and decreases work of breathing."
  },
  {
    id: "COPD-003",
    caseId: "COPD-CASE-001",
    patient: "Mr. David Lewis",
    topic: "COPD",
    subtopic: "Breathing Technique",
    style: "Teaching",
    difficulty: "ATI",
    question: "Which teaching should the nurse provide to help Mr. Lewis during episodes of shortness of breath?",
    choices: ["Use pursed-lip breathing", "Hold your breath", "Breathe rapidly through your mouth", "Lie flat until symptoms pass"],
    answer: "Use pursed-lip breathing",
    rationale: "Pursed-lip breathing helps keep airways open longer and improves ventilation."
  },
  {
    id: "COPD-004",
    caseId: "COPD-CASE-002",
    patient: "Ms. Carol Jenkins",
    topic: "COPD",
    subtopic: "CO2 Retention",
    style: "Analyze Cues",
    difficulty: "ATI",
    question: "Ms. Jenkins has COPD and is becoming drowsy and confused. ABGs show pH 7.30, PaCO₂ 58, HCO₃⁻ 27. Which condition is most likely?",
    choices: ["Respiratory acidosis", "Respiratory alkalosis", "Metabolic acidosis", "Metabolic alkalosis"],
    answer: "Respiratory acidosis",
    rationale: "COPD patients can retain CO₂ due to hypoventilation. High PaCO₂ with low pH indicates respiratory acidosis."
  },
  {
    id: "COPD-005",
    caseId: "COPD-CASE-002",
    patient: "Ms. Carol Jenkins",
    topic: "COPD",
    subtopic: "CO2 Retention",
    style: "Priority",
    difficulty: "ATI",
    question: "Ms. Jenkins is becoming increasingly difficult to arouse. What is the nurse's priority?",
    choices: ["Support airway and ventilation", "Encourage oral intake", "Turn off oxygen", "Ask about home diet"],
    answer: "Support airway and ventilation",
    rationale: "Decreased level of consciousness with CO₂ retention is dangerous. Airway and breathing are the priority."
  },
  {
    id: "COPD-006",
    caseId: "COPD-CASE-002",
    patient: "Ms. Carol Jenkins",
    topic: "COPD",
    subtopic: "Evaluation",
    style: "Evaluation",
    difficulty: "ATI",
    question: "Which finding suggests Ms. Jenkins is improving?",
    choices: ["PaCO₂ decreases toward 45 mmHg", "PaCO₂ increases to 70 mmHg", "Confusion worsens", "Respirations become more shallow"],
    answer: "PaCO₂ decreases toward 45 mmHg",
    rationale: "A PaCO₂ moving toward the normal range indicates improved ventilation."
  },
  {
    id: "COPD-007",
    caseId: "COPD-CASE-003",
    patient: "Mr. Allen Brooks",
    topic: "COPD",
    subtopic: "Oxygen Therapy",
    style: "Safety",
    difficulty: "ATI",
    question: "Mr. Brooks has COPD and is prescribed controlled oxygen therapy. Which device may be used to deliver a precise oxygen concentration?",
    choices: ["Venturi mask", "Room air only", "Nonsterile face cloth", "Chest tube"],
    answer: "Venturi mask",
    rationale: "A Venturi mask delivers a precise FiO₂ and is often used when accurate oxygen concentration is needed."
  },
  {
    id: "COPD-008",
    caseId: "COPD-CASE-003",
    patient: "Mr. Allen Brooks",
    topic: "COPD",
    subtopic: "Oxygen Monitoring",
    style: "Priority",
    difficulty: "ATI",
    question: "Mr. Brooks is receiving oxygen. Which assessment should the nurse monitor closely?",
    choices: ["Respiratory status and mental status", "Hair growth", "Appetite only", "Skin color only"],
    answer: "Respiratory status and mental status",
    rationale: "COPD patients receiving oxygen should be monitored for respiratory effort, oxygenation, and signs of CO₂ retention such as drowsiness or confusion."
  },
  {
    id: "COPD-009",
    caseId: "COPD-CASE-004",
    patient: "Ms. Gloria White",
    topic: "COPD",
    subtopic: "Expected Findings",
    style: "Recognition",
    difficulty: "Basic",
    question: "Ms. White has long-term COPD. Which finding would the nurse expect?",
    choices: ["Barrel chest", "Sudden hypoglycemia", "Tetany", "Flat neck veins always"],
    answer: "Barrel chest",
    rationale: "Barrel chest may occur in chronic COPD due to air trapping and hyperinflation."
  },
  {
    id: "COPD-010",
    caseId: "COPD-CASE-004",
    patient: "Ms. Gloria White",
    topic: "COPD",
    subtopic: "Unexpected Findings",
    style: "Analyze Cues",
    difficulty: "ATI",
    question: "Which finding in Ms. White requires the most immediate follow-up?",
    choices: ["New confusion", "Chronic cough", "History of smoking", "Mild activity intolerance"],
    answer: "New confusion",
    rationale: "New confusion can indicate worsening hypoxia or CO₂ retention and requires immediate assessment."
  },
  {
    id: "COPD-011",
    caseId: "COPD-CASE-005",
    patient: "Mr. Frank Hill",
    topic: "COPD",
    subtopic: "Medication",
    style: "Application",
    difficulty: "ATI",
    question: "Mr. Hill is wheezing during a COPD exacerbation. Which medication would the nurse expect to help open the airways?",
    choices: ["Bronchodilator", "Antacid", "Potassium supplement only", "Calcium carbonate"],
    answer: "Bronchodilator",
    rationale: "Bronchodilators relax airway smooth muscle and help improve airflow in obstructive lung disease."
  },
  {
    id: "COPD-012",
    caseId: "COPD-CASE-005",
    patient: "Mr. Frank Hill",
    topic: "COPD",
    subtopic: "Evaluation",
    style: "Evaluation",
    difficulty: "ATI",
    question: "Which finding indicates the bronchodilator was effective?",
    choices: ["Decreased wheezing and easier breathing", "Increased dyspnea", "SpO₂ drops further", "Accessory muscle use worsens"],
    answer: "Decreased wheezing and easier breathing",
    rationale: "Improved airflow is shown by decreased wheezing, less dyspnea, and reduced work of breathing."
  },
  {
    id: "COPD-013",
    caseId: "COPD-CASE-006",
    patient: "Ms. Sharon King",
    topic: "COPD",
    subtopic: "Infection",
    style: "Recognition",
    difficulty: "ATI",
    question: "Ms. King has COPD and reports increased sputum production, fever, and worsening shortness of breath. What complication is the nurse concerned about?",
    choices: ["Respiratory infection", "Hypercalcemia", "Metabolic alkalosis only", "Hypoglycemia"],
    answer: "Respiratory infection",
    rationale: "Increased sputum, fever, and worsening dyspnea may indicate respiratory infection, which can worsen COPD."
  },
  {
    id: "COPD-014",
    caseId: "COPD-CASE-006",
    patient: "Ms. Sharon King",
    topic: "COPD",
    subtopic: "Priority",
    style: "Priority",
    difficulty: "ATI",
    question: "Ms. King has fever, increased sputum, and SpO₂ 85%. What should the nurse prioritize?",
    choices: ["Assess oxygenation and notify the provider", "Delay care until discharge", "Encourage smoking", "Restrict all respiratory treatments"],
    answer: "Assess oxygenation and notify the provider",
    rationale: "Worsening oxygenation with possible infection requires prompt assessment and provider notification."
  },
  {
    id: "COPD-015",
    caseId: "COPD-CASE-007",
    patient: "Mr. Raymond Bell",
    topic: "COPD",
    subtopic: "Energy Conservation",
    style: "Teaching",
    difficulty: "Basic",
    question: "Mr. Bell has COPD and becomes short of breath during ADLs. Which teaching is most appropriate?",
    choices: ["Plan rest periods between activities", "Rush through care quickly", "Avoid all activity forever", "Hold breath while walking"],
    answer: "Plan rest periods between activities",
    rationale: "Energy conservation helps reduce oxygen demand and dyspnea during daily activities."
  },
  {
    id: "COPD-016",
    caseId: "COPD-CASE-007",
    patient: "Mr. Raymond Bell",
    topic: "COPD",
    subtopic: "Activity",
    style: "Evaluation",
    difficulty: "Basic",
    question: "Which statement shows Mr. Bell understands energy conservation?",
    choices: ["I will pace myself and rest before I get too short of breath", "I should avoid all walking", "I should hold my breath during activity", "I should skip my inhalers before activity"],
    answer: "I will pace myself and rest before I get too short of breath",
    rationale: "Pacing activity and resting reduce oxygen demand and help manage dyspnea."
  },
  {
    id: "COPD-017",
    caseId: "COPD-CASE-008",
    patient: "Ms. Patricia Adams",
    topic: "COPD",
    subtopic: "Smoking",
    style: "Teaching",
    difficulty: "Basic",
    question: "Ms. Adams has COPD and smokes daily. Which teaching is most important?",
    choices: ["Smoking cessation is the most important lifestyle change", "Smoking improves oxygenation", "Only stop smoking during infections", "Use oxygen while smoking"],
    answer: "Smoking cessation is the most important lifestyle change",
    rationale: "Smoking cessation slows disease progression and improves outcomes in COPD."
  },
  {
    id: "COPD-018",
    caseId: "COPD-CASE-008",
    patient: "Ms. Patricia Adams",
    topic: "COPD",
    subtopic: "Home Oxygen Safety",
    style: "Safety",
    difficulty: "ATI",
    question: "Ms. Adams uses home oxygen. Which statement requires correction?",
    choices: ["I can smoke if I remove the nasal cannula", "I will keep oxygen away from flames", "I will post no-smoking signs", "I will use oxygen as prescribed"],
    answer: "I can smoke if I remove the nasal cannula",
    rationale: "Smoking near oxygen is extremely dangerous. Oxygen supports combustion and increases fire risk."
  },
  {
    id: "COPD-019",
    caseId: "COPD-CASE-009",
    patient: "Mr. Samuel Wright",
    topic: "COPD",
    subtopic: "SATA",
    style: "SATA",
    difficulty: "ATI",
    question: "Mr. Wright has COPD. Which interventions may help improve breathing? Select all that apply.",
    choices: ["High Fowler's position", "Pursed-lip breathing", "Bronchodilator as prescribed", "Energy conservation", "Smoking while using oxygen"],
    answer: ["High Fowler's position", "Pursed-lip breathing", "Bronchodilator as prescribed", "Energy conservation"],
    rationale: "Positioning, breathing techniques, bronchodilators, and energy conservation can help COPD patients. Smoking with oxygen is unsafe."
  },
  {
    id: "COPD-020",
    caseId: "COPD-CASE-010",
    patient: "Ms. Diane Lopez",
    topic: "COPD",
    subtopic: "Clinical Judgment",
    style: "Priority",
    difficulty: "ATI",
    question: "Ms. Lopez with COPD has SpO₂ 82%, confusion, and shallow respirations. Which action is most appropriate?",
    choices: ["Stay with the patient, support breathing, and call for help", "Leave the room to get lunch trays", "Turn off oxygen", "Document as expected aging"],
    answer: "Stay with the patient, support breathing, and call for help",
    rationale: "Severe hypoxemia and altered mental status require immediate intervention and escalation of care."
  }
];