const hypoxiaQuestions = [
  {
    id: "HY-001",
    caseId: "HY-CASE-001",
    patient: "Mr. Nolan Green",
    topic: "Hypoxia",
    subtopic: "Early Signs",
    style: "Recognition",
    difficulty: "ATI",
    question: "Mr. Green is admitted with pneumonia. He becomes restless, anxious, and mildly confused. SpO₂ is 88%. Which problem is most likely?",
    choices: ["Hypoxia", "Hypercalcemia", "Fluid volume excess only", "Metabolic alkalosis"],
    answer: "Hypoxia",
    rationale: "Restlessness, anxiety, confusion, and low SpO₂ are common signs of decreased oxygenation."
  },
  {
    id: "HY-002",
    caseId: "HY-CASE-001",
    patient: "Mr. Nolan Green",
    topic: "Hypoxia",
    subtopic: "Priority",
    style: "Priority",
    difficulty: "ATI",
    question: "Mr. Green's SpO₂ drops to 86% and he is confused. What should the nurse do first?",
    choices: ["Assess airway and breathing", "Offer a snack", "Ask about bowel habits", "Document and reassess tomorrow"],
    answer: "Assess airway and breathing",
    rationale: "Airway and breathing are priority. Hypoxia can quickly become life-threatening."
  },
  {
    id: "HY-003",
    caseId: "HY-CASE-002",
    patient: "Ms. Ava Turner",
    topic: "Hypoxia",
    subtopic: "Late Signs",
    style: "Analyze Cues",
    difficulty: "ATI",
    question: "Ms. Turner has worsening hypoxia. Which finding is most concerning?",
    choices: ["Cyanosis", "Mild thirst", "Increased appetite", "Dry skin only"],
    answer: "Cyanosis",
    rationale: "Cyanosis is a late and concerning sign of poor oxygenation."
  },
  {
    id: "HY-004",
    caseId: "HY-CASE-002",
    patient: "Ms. Ava Turner",
    topic: "Hypoxia",
    subtopic: "Mental Status",
    style: "Recognition",
    difficulty: "ATI",
    question: "Which change may be an early sign that Ms. Turner is not getting enough oxygen?",
    choices: ["New confusion", "Improved appetite", "Decreased pain", "Normal speech"],
    answer: "New confusion",
    rationale: "The brain is sensitive to low oxygen. Restlessness and confusion can be early signs of hypoxia."
  },
  {
    id: "HY-005",
    caseId: "HY-CASE-003",
    patient: "Mr. Caleb Morris",
    topic: "Hypoxia",
    subtopic: "Assessment",
    style: "Priority",
    difficulty: "ATI",
    question: "Mr. Morris reports shortness of breath. Which assessment is most important?",
    choices: ["Respiratory rate, SpO₂, work of breathing, and lung sounds", "Hair texture", "Meal preference", "Last bowel movement only"],
    answer: "Respiratory rate, SpO₂, work of breathing, and lung sounds",
    rationale: "A focused respiratory assessment helps determine severity and guides oxygenation interventions."
  },
  {
    id: "HY-006",
    caseId: "HY-CASE-003",
    patient: "Mr. Caleb Morris",
    topic: "Hypoxia",
    subtopic: "Positioning",
    style: "Take Action",
    difficulty: "Basic",
    question: "Mr. Morris is dyspneic and sitting low in bed. Which action should the nurse take?",
    choices: ["Place him in high Fowler's position", "Lay him flat", "Place him in Trendelenburg", "Turn off oxygen"],
    answer: "Place him in high Fowler's position",
    rationale: "High Fowler's promotes lung expansion and can reduce work of breathing."
  },
  {
    id: "HY-007",
    caseId: "HY-CASE-004",
    patient: "Ms. Elena Hill",
    topic: "Hypoxia",
    subtopic: "Escalation",
    style: "Priority",
    difficulty: "ATI",
    question: "Ms. Hill is receiving oxygen by nasal cannula, but SpO₂ remains 84% and she is increasingly drowsy. What should the nurse do?",
    choices: ["Notify the provider and prepare to escalate oxygen therapy", "Remove oxygen", "Wait for the next scheduled vital signs", "Encourage sleep only"],
    answer: "Notify the provider and prepare to escalate oxygen therapy",
    rationale: "Persistent hypoxia with decreased level of consciousness requires urgent escalation."
  },
  {
    id: "HY-008",
    caseId: "HY-CASE-004",
    patient: "Ms. Elena Hill",
    topic: "Hypoxia",
    subtopic: "Clinical Judgment",
    style: "Analyze Cues",
    difficulty: "ATI",
    question: "Which cue best indicates Ms. Hill's condition is worsening?",
    choices: ["Increasing drowsiness", "Reports feeling hungry", "Skin warm and dry", "Requests a blanket"],
    answer: "Increasing drowsiness",
    rationale: "Decreasing level of consciousness can indicate worsening oxygenation or ventilation."
  },
  {
    id: "HY-009",
    caseId: "HY-CASE-005",
    patient: "Mr. Owen Scott",
    topic: "Hypoxia",
    subtopic: "Evaluation",
    style: "Evaluation",
    difficulty: "Basic",
    question: "Mr. Scott receives oxygen and is repositioned. Which finding indicates improvement?",
    choices: ["SpO₂ increases from 87% to 95%", "Respirations increase to 40/min", "Confusion worsens", "Cyanosis develops"],
    answer: "SpO₂ increases from 87% to 95%",
    rationale: "An increased SpO₂ with improved symptoms indicates better oxygenation."
  },
  {
    id: "HY-010",
    caseId: "HY-CASE-005",
    patient: "Mr. Owen Scott",
    topic: "Hypoxia",
    subtopic: "Evaluation",
    style: "Evaluation",
    difficulty: "ATI",
    question: "Which finding would indicate the intervention has NOT been effective?",
    choices: ["SpO₂ remains 84%", "Patient is less anxious", "Respiratory rate decreases to 18/min", "Skin color improves"],
    answer: "SpO₂ remains 84%",
    rationale: "Persistent low oxygen saturation indicates ongoing hypoxia and need for further intervention."
  },
  {
    id: "HY-011",
    caseId: "HY-CASE-006",
    patient: "Ms. Hannah Lewis",
    topic: "Hypoxia",
    subtopic: "Pulse Oximetry",
    style: "Safety",
    difficulty: "ATI",
    question: "Ms. Lewis has a pulse oximeter reading of 82%, but the waveform is poor and her hands are cold. What should the nurse do first?",
    choices: ["Reassess the sensor and patient condition", "Ignore the reading completely", "Call the family", "Remove oxygen permanently"],
    answer: "Reassess the sensor and patient condition",
    rationale: "Pulse oximetry can be inaccurate with poor perfusion. The nurse should assess the patient and verify the reading."
  },
  {
    id: "HY-012",
    caseId: "HY-CASE-006",
    patient: "Ms. Hannah Lewis",
    topic: "Hypoxia",
    subtopic: "Priority Assessment",
    style: "Priority",
    difficulty: "ATI",
    question: "Which finding matters most when deciding if Ms. Lewis is truly hypoxic?",
    choices: ["Work of breathing and mental status", "Favorite food", "Hair color", "Height"],
    answer: "Work of breathing and mental status",
    rationale: "Clinical assessment is essential. Work of breathing and mental status help confirm oxygenation problems."
  },
  {
    id: "HY-013",
    caseId: "HY-CASE-007",
    patient: "Mr. Victor Adams",
    topic: "Hypoxia",
    subtopic: "Severe Hypoxemia",
    style: "Recognition",
    difficulty: "ATI",
    question: "Mr. Adams' ABG shows PaO₂ 55 mmHg. What does this indicate?",
    choices: ["Severe hypoxemia", "Normal oxygenation", "Metabolic acidosis", "Respiratory alkalosis"],
    answer: "Severe hypoxemia",
    rationale: "PaO₂ below 60 mmHg is a critical finding and indicates severe hypoxemia."
  },
  {
    id: "HY-014",
    caseId: "HY-CASE-007",
    patient: "Mr. Victor Adams",
    topic: "Hypoxia",
    subtopic: "ABG Priority",
    style: "Priority",
    difficulty: "ATI",
    question: "Mr. Adams has PaO₂ 55 mmHg. What is the priority nursing focus?",
    choices: ["Improve oxygenation", "Treat constipation", "Restrict all fluids", "Teach low sodium diet only"],
    answer: "Improve oxygenation",
    rationale: "Low PaO₂ is an oxygenation problem and requires prompt intervention."
  },
  {
    id: "HY-015",
    caseId: "HY-CASE-008",
    patient: "Ms. Grace Young",
    topic: "Hypoxia",
    subtopic: "SATA",
    style: "SATA",
    difficulty: "ATI",
    question: "Ms. Young may be developing hypoxia. Which findings should the nurse recognize? Select all that apply.",
    choices: ["Restlessness", "Confusion", "Low SpO₂", "Cyanosis", "Improved alertness"],
    answer: ["Restlessness", "Confusion", "Low SpO₂", "Cyanosis"],
    rationale: "Signs of hypoxia include restlessness, confusion, low oxygen saturation, cyanosis, dyspnea, and increased work of breathing."
  }
];