const pneumoniaQuestions = [
  {
    id: "PNA-001",
    caseId: "PNA-CASE-001",
    patient: "Mr. Michael Brown",
    topic: "Pneumonia",
    subtopic: "Recognition",
    style: "Recognition",
    difficulty: "ATI",
    question: "Mr. Brown has fever, productive cough, crackles in the right lower lobe, fatigue, and SpO₂ 89%. Which condition is most likely?",
    choices: ["Pneumonia", "Hypocalcemia", "Metabolic alkalosis", "Hyperkalemia"],
    answer: "Pneumonia",
    rationale: "Fever, productive cough, crackles, fatigue, and decreased oxygen saturation are consistent with pneumonia."
  },
  {
    id: "PNA-002",
    caseId: "PNA-CASE-001",
    patient: "Mr. Michael Brown",
    topic: "Pneumonia",
    subtopic: "Priority",
    style: "Priority",
    difficulty: "ATI",
    question: "Mr. Brown is restless and his SpO₂ is 86%. What should the nurse do first?",
    choices: ["Assess airway and breathing", "Offer a meal tray", "Delay care until morning", "Encourage bedrest only"],
    answer: "Assess airway and breathing",
    rationale: "Low oxygen saturation with restlessness suggests hypoxia. Airway and breathing are the priority."
  },
  {
    id: "PNA-003",
    caseId: "PNA-CASE-001",
    patient: "Mr. Michael Brown",
    topic: "Pneumonia",
    subtopic: "Assessment",
    style: "Analyze Cues",
    difficulty: "ATI",
    question: "Which finding is most concerning in Mr. Brown?",
    choices: ["New confusion", "Mild fatigue", "Productive cough", "Low-grade fever"],
    answer: "New confusion",
    rationale: "New confusion may indicate worsening hypoxia or sepsis and requires prompt follow-up."
  },
  {
    id: "PNA-004",
    caseId: "PNA-CASE-002",
    patient: "Ms. Laura Evans",
    topic: "Pneumonia",
    subtopic: "Interventions",
    style: "Take Action",
    difficulty: "Basic",
    question: "Ms. Evans has pneumonia and thick secretions. Which nursing intervention helps mobilize secretions?",
    choices: ["Encourage fluids if not contraindicated", "Keep her flat in bed", "Restrict coughing", "Avoid repositioning"],
    answer: "Encourage fluids if not contraindicated",
    rationale: "Fluids can help thin secretions, making them easier to cough up."
  },
  {
    id: "PNA-005",
    caseId: "PNA-CASE-002",
    patient: "Ms. Laura Evans",
    topic: "Pneumonia",
    subtopic: "Positioning",
    style: "Take Action",
    difficulty: "Basic",
    question: "Ms. Evans is short of breath. Which position should the nurse use?",
    choices: ["High Fowler's", "Supine and flat", "Trendelenburg", "Prone with head flat"],
    answer: "High Fowler's",
    rationale: "High Fowler's promotes lung expansion and improves breathing comfort."
  },
  {
    id: "PNA-006",
    caseId: "PNA-CASE-003",
    patient: "Mr. Henry Adams",
    topic: "Pneumonia",
    subtopic: "Diagnostics",
    style: "Application",
    difficulty: "ATI",
    question: "Mr. Adams has suspected pneumonia. Which diagnostic finding would support this diagnosis?",
    choices: ["Chest x-ray showing infiltrates", "Normal lung sounds only", "Negative sputum culture always", "Low calcium level only"],
    answer: "Chest x-ray showing infiltrates",
    rationale: "Chest x-ray infiltrates support pneumonia when paired with clinical symptoms such as fever, cough, and crackles."
  },
  {
    id: "PNA-007",
    caseId: "PNA-CASE-003",
    patient: "Mr. Henry Adams",
    topic: "Pneumonia",
    subtopic: "Sputum Culture",
    style: "Safety",
    difficulty: "ATI",
    question: "A sputum culture is ordered before antibiotics. What should the nurse do?",
    choices: ["Collect the sputum specimen before starting antibiotics if possible", "Start antibiotics and ignore the culture", "Collect saliva only", "Delay antibiotics for several days"],
    answer: "Collect the sputum specimen before starting antibiotics if possible",
    rationale: "Cultures are ideally collected before antibiotics so the organism can be identified accurately."
  },
  {
    id: "PNA-008",
    caseId: "PNA-CASE-004",
    patient: "Ms. Denise Hall",
    topic: "Pneumonia",
    subtopic: "Antibiotics",
    style: "Evaluation",
    difficulty: "ATI",
    question: "Ms. Hall started antibiotics for bacterial pneumonia. Which finding suggests treatment is effective?",
    choices: ["Temperature decreases and breathing improves", "Fever rises to 104°F", "SpO₂ drops to 82%", "Confusion worsens"],
    answer: "Temperature decreases and breathing improves",
    rationale: "Improved temperature, respiratory status, oxygenation, and energy level suggest antibiotic therapy is helping."
  },
  {
    id: "PNA-009",
    caseId: "PNA-CASE-004",
    patient: "Ms. Denise Hall",
    topic: "Pneumonia",
    subtopic: "Evaluation",
    style: "Evaluation",
    difficulty: "ATI",
    question: "Which finding indicates Ms. Hall is worsening?",
    choices: ["Increasing respiratory distress", "Improved appetite", "SpO₂ increases", "Cough decreases"],
    answer: "Increasing respiratory distress",
    rationale: "Increasing respiratory distress indicates worsening oxygenation and requires prompt intervention."
  },
  {
    id: "PNA-010",
    caseId: "PNA-CASE-005",
    patient: "Mr. Robert Jones",
    topic: "Pneumonia",
    subtopic: "Older Adult",
    style: "Recognition",
    difficulty: "ATI",
    question: "Mr. Jones is an older adult with pneumonia. He has no fever but is newly confused and weak. What should the nurse understand?",
    choices: ["Older adults may show atypical signs of infection", "Pneumonia is impossible without fever", "Confusion is always normal aging", "Weakness rules out infection"],
    answer: "Older adults may show atypical signs of infection",
    rationale: "Older adults may have pneumonia with atypical symptoms such as confusion, weakness, or decreased appetite rather than fever."
  },
  {
    id: "PNA-011",
    caseId: "PNA-CASE-005",
    patient: "Mr. Robert Jones",
    topic: "Pneumonia",
    subtopic: "Priority",
    style: "Priority",
    difficulty: "ATI",
    question: "Mr. Jones is newly confused with SpO₂ 88%. What should the nurse do first?",
    choices: ["Assess oxygenation and respiratory status", "Assume dementia", "Offer a sleeping pill", "Wait for family to arrive"],
    answer: "Assess oxygenation and respiratory status",
    rationale: "New confusion with low oxygen saturation can indicate hypoxia and requires immediate respiratory assessment."
  },
  {
    id: "PNA-012",
    caseId: "PNA-CASE-006",
    patient: "Ms. Natalie Wood",
    topic: "Pneumonia",
    subtopic: "Prevention",
    style: "Teaching",
    difficulty: "Basic",
    question: "Ms. Wood asks how to reduce the risk of pneumonia. Which teaching is appropriate?",
    choices: ["Perform hand hygiene and stay current with recommended vaccines", "Avoid coughing forever", "Take leftover antibiotics", "Stay in bed all day"],
    answer: "Perform hand hygiene and stay current with recommended vaccines",
    rationale: "Hand hygiene, vaccines, mobility, coughing/deep breathing, and avoiding smoking can help reduce pneumonia risk."
  },
  {
    id: "PNA-013",
    caseId: "PNA-CASE-006",
    patient: "Ms. Natalie Wood",
    topic: "Pneumonia",
    subtopic: "Postoperative Prevention",
    style: "Teaching",
    difficulty: "ATI",
    question: "A postoperative patient asks why they need incentive spirometry. What is the best response?",
    choices: ["It helps expand the lungs and reduce atelectasis and pneumonia risk", "It replaces all ambulation", "It causes pneumonia", "It is only for patients with fractures"],
    answer: "It helps expand the lungs and reduce atelectasis and pneumonia risk",
    rationale: "Incentive spirometry promotes deep breathing, lung expansion, and prevention of atelectasis and pneumonia."
  },
  {
    id: "PNA-014",
    caseId: "PNA-CASE-007",
    patient: "Mr. Tyler James",
    topic: "Pneumonia",
    subtopic: "Airway Clearance",
    style: "Take Action",
    difficulty: "ATI",
    question: "Mr. James has pneumonia and a weak cough. Which action should the nurse prioritize?",
    choices: ["Encourage coughing, deep breathing, and repositioning", "Discourage coughing", "Keep him flat", "Avoid assessing lung sounds"],
    answer: "Encourage coughing, deep breathing, and repositioning",
    rationale: "Coughing, deep breathing, and repositioning support airway clearance and lung expansion."
  },
  {
    id: "PNA-015",
    caseId: "PNA-CASE-007",
    patient: "Mr. Tyler James",
    topic: "Pneumonia",
    subtopic: "SATA",
    style: "SATA",
    difficulty: "ATI",
    question: "Which findings may be seen in pneumonia? Select all that apply.",
    choices: ["Fever", "Productive cough", "Crackles", "Low SpO₂", "Improved oxygenation without treatment"],
    answer: ["Fever", "Productive cough", "Crackles", "Low SpO₂"],
    rationale: "Pneumonia can cause fever, productive cough, crackles, dyspnea, fatigue, and decreased oxygenation."
  }
];