const respiratoryFailureQuestions = [
  {
    id: "RF-001",
    caseId: "RF-CASE-001",
    patient: "Mr. Nolan Hayes",
    topic: "Respiratory Failure",
    subtopic: "Recognition",
    style: "Recognition",
    difficulty: "ATI",
    question: "Mr. Hayes has pneumonia and becomes confused, restless, and severely short of breath. SpO₂ is 82% on oxygen. Which problem is most likely developing?",
    choices: ["Respiratory failure", "Hypocalcemia", "Metabolic alkalosis", "Fluid volume deficit only"],
    answer: "Respiratory failure",
    rationale: "Respiratory failure occurs when the lungs cannot adequately oxygenate the blood or remove CO₂. Severe hypoxemia, confusion, and respiratory distress are warning signs."
  },
  {
    id: "RF-002",
    caseId: "RF-CASE-001",
    patient: "Mr. Nolan Hayes",
    topic: "Respiratory Failure",
    subtopic: "Priority",
    style: "Priority",
    difficulty: "ATI",
    question: "Mr. Hayes has SpO₂ 82%, severe dyspnea, and confusion. What is the nurse's priority?",
    choices: ["Support oxygenation and call for rapid assistance", "Offer oral fluids", "Complete discharge teaching", "Reassess tomorrow"],
    answer: "Support oxygenation and call for rapid assistance",
    rationale: "Severe hypoxemia and altered mental status indicate a respiratory emergency. Airway and breathing are priority."
  },
  {
    id: "RF-003",
    caseId: "RF-CASE-002",
    patient: "Ms. Angela Turner",
    topic: "Respiratory Failure",
    subtopic: "Hypoxemic Respiratory Failure",
    style: "Analyze Cues",
    difficulty: "ATI",
    question: "Ms. Turner has PaO₂ 54 mmHg despite oxygen therapy. What does this indicate?",
    choices: ["Severe hypoxemia", "Normal oxygenation", "Metabolic alkalosis", "Respiratory alkalosis only"],
    answer: "Severe hypoxemia",
    rationale: "A PaO₂ below 60 mmHg is a critical oxygenation finding and may indicate hypoxemic respiratory failure."
  },
  {
    id: "RF-004",
    caseId: "RF-CASE-002",
    patient: "Ms. Angela Turner",
    topic: "Respiratory Failure",
    subtopic: "Evaluation",
    style: "Evaluation",
    difficulty: "ATI",
    question: "Which finding shows Ms. Turner's oxygenation is improving?",
    choices: ["PaO₂ rises from 54 to 82 mmHg", "SpO₂ drops to 78%", "Confusion worsens", "Cyanosis develops"],
    answer: "PaO₂ rises from 54 to 82 mmHg",
    rationale: "A PaO₂ returning toward the normal range of 80–100 mmHg shows improved oxygenation."
  },
  {
    id: "RF-005",
    caseId: "RF-CASE-003",
    patient: "Mr. Charles Bennett",
    topic: "Respiratory Failure",
    subtopic: "Hypercapnic Respiratory Failure",
    style: "Recognition",
    difficulty: "ATI",
    question: "Mr. Bennett has COPD and becomes drowsy with shallow respirations. ABGs show pH 7.28 and PaCO₂ 68. Which problem is most likely?",
    choices: ["Hypercapnic respiratory failure", "Metabolic alkalosis", "Hypocalcemia", "Normal ABG"],
    answer: "Hypercapnic respiratory failure",
    rationale: "High PaCO₂ with low pH indicates CO₂ retention and respiratory acidosis. In COPD this may progress to hypercapnic respiratory failure."
  },
  {
    id: "RF-006",
    caseId: "RF-CASE-003",
    patient: "Mr. Charles Bennett",
    topic: "Respiratory Failure",
    subtopic: "CO2 Retention",
    style: "Priority",
    difficulty: "ATI",
    question: "Mr. Bennett is difficult to arouse and retaining CO₂. What should the nurse do first?",
    choices: ["Maintain airway and support ventilation", "Encourage independent ambulation", "Give a large meal", "Delay care until family arrives"],
    answer: "Maintain airway and support ventilation",
    rationale: "CO₂ retention with decreasing level of consciousness threatens airway and breathing. Ventilation support is priority."
  },
  {
    id: "RF-007",
    caseId: "RF-CASE-004",
    patient: "Ms. Patricia Green",
    topic: "Respiratory Failure",
    subtopic: "Clinical Deterioration",
    style: "Analyze Cues",
    difficulty: "ATI",
    question: "Ms. Green has increasing restlessness, tachypnea, cyanosis, and falling SpO₂. Which interpretation is most appropriate?",
    choices: ["Her respiratory status is worsening", "She is ready for discharge", "This is expected after eating", "Her oxygenation is improving"],
    answer: "Her respiratory status is worsening",
    rationale: "Restlessness, cyanosis, tachypnea, and falling SpO₂ are signs of worsening oxygenation and possible respiratory failure."
  },
  {
    id: "RF-008",
    caseId: "RF-CASE-004",
    patient: "Ms. Patricia Green",
    topic: "Respiratory Failure",
    subtopic: "Escalation",
    style: "Take Action",
    difficulty: "ATI",
    question: "Ms. Green is rapidly deteriorating despite oxygen therapy. What should the nurse anticipate?",
    choices: ["Escalation to advanced airway or ventilatory support", "Stopping all respiratory treatment", "Immediate discharge", "Restricting all assessments"],
    answer: "Escalation to advanced airway or ventilatory support",
    rationale: "Worsening respiratory failure may require noninvasive ventilation, intubation, or mechanical ventilation depending on severity."
  },
  {
    id: "RF-009",
    caseId: "RF-CASE-005",
    patient: "Mr. Daniel Foster",
    topic: "Respiratory Failure",
    subtopic: "Assessment",
    style: "Priority",
    difficulty: "ATI",
    question: "Which assessment is most important for Mr. Foster with suspected respiratory failure?",
    choices: ["Respiratory effort, SpO₂, lung sounds, and mental status", "Hair color", "Meal preference", "Vision test"],
    answer: "Respiratory effort, SpO₂, lung sounds, and mental status",
    rationale: "Respiratory failure threatens oxygenation and ventilation. Work of breathing and mental status are key clinical cues."
  },
  {
    id: "RF-010",
    caseId: "RF-CASE-005",
    patient: "Mr. Daniel Foster",
    topic: "Respiratory Failure",
    subtopic: "Safety",
    style: "Safety",
    difficulty: "ATI",
    question: "Which finding should the nurse report immediately?",
    choices: ["Decreasing level of consciousness", "Mild thirst", "Stable vital signs", "Improved oxygen saturation"],
    answer: "Decreasing level of consciousness",
    rationale: "A declining level of consciousness may indicate worsening hypoxia or CO₂ retention and requires immediate intervention."
  },
  {
    id: "RF-011",
    caseId: "RF-CASE-006",
    patient: "Ms. Nora Hill",
    topic: "Respiratory Failure",
    subtopic: "ABG Interpretation",
    style: "Analyze Cues",
    difficulty: "ATI",
    question: "Ms. Hill has ABGs: pH 7.31, PaCO₂ 60, PaO₂ 58, HCO₃⁻ 26. What is the priority concern?",
    choices: ["Respiratory acidosis with hypoxemia", "Normal oxygenation", "Metabolic alkalosis", "Fully compensated metabolic acidosis"],
    answer: "Respiratory acidosis with hypoxemia",
    rationale: "Low pH and high PaCO₂ indicate respiratory acidosis. PaO₂ below 60 indicates severe hypoxemia."
  },
  {
    id: "RF-012",
    caseId: "RF-CASE-006",
    patient: "Ms. Nora Hill",
    topic: "Respiratory Failure",
    subtopic: "Priority",
    style: "Priority",
    difficulty: "ATI",
    question: "Based on Ms. Hill's ABGs and respiratory distress, what is the nurse's priority?",
    choices: ["Support oxygenation and ventilation", "Teach low-sodium diet", "Assess bowel sounds only", "Encourage sleep"],
    answer: "Support oxygenation and ventilation",
    rationale: "Both oxygenation and ventilation are impaired. Airway and breathing interventions are priority."
  },
  {
    id: "RF-013",
    caseId: "RF-CASE-007",
    patient: "Mr. Eric Wilson",
    topic: "Respiratory Failure",
    subtopic: "Evaluation",
    style: "Evaluation",
    difficulty: "ATI",
    question: "Mr. Wilson is treated for respiratory failure. Which finding indicates improvement?",
    choices: ["Less work of breathing and SpO₂ 95%", "Increasing cyanosis", "PaO₂ remains 50", "Patient becomes unresponsive"],
    answer: "Less work of breathing and SpO₂ 95%",
    rationale: "Reduced work of breathing and improved oxygen saturation indicate improved respiratory status."
  },
  {
    id: "RF-014",
    caseId: "RF-CASE-007",
    patient: "Mr. Eric Wilson",
    topic: "Respiratory Failure",
    subtopic: "Evaluation",
    style: "Evaluation",
    difficulty: "ATI",
    question: "Which finding indicates treatment is not effective?",
    choices: ["SpO₂ remains 82% with confusion", "Patient is alert", "Respiratory rate normalizes", "Breath sounds improve"],
    answer: "SpO₂ remains 82% with confusion",
    rationale: "Persistent hypoxemia with confusion shows ongoing respiratory compromise."
  },
  {
    id: "RF-015",
    caseId: "RF-CASE-008",
    patient: "Ms. Hannah Cole",
    topic: "Respiratory Failure",
    subtopic: "Clinical Judgment",
    style: "Priority",
    difficulty: "ATI",
    question: "Ms. Cole is in acute respiratory distress. Which action best reflects the nurse's priority?",
    choices: ["Stay with the patient, call for help, and support breathing", "Leave to finish charting", "Offer oral fluids first", "Wait for routine vital signs"],
    answer: "Stay with the patient, call for help, and support breathing",
    rationale: "Acute respiratory distress requires immediate nursing presence, escalation, and oxygenation/ventilation support."
  }
];