const tracheostomyQuestions = [
  {
    id: "TRACH-001",
    caseId: "TRACH-CASE-001",
    patient: "Mr. Carl Simmons",
    topic: "Tracheostomy",
    subtopic: "Airway Priority",
    style: "Priority",
    difficulty: "ATI",
    question: "Mr. Simmons has a new tracheostomy and suddenly becomes restless with noisy respirations. What should the nurse do first?",
    choices: ["Assess airway patency", "Offer oral fluids", "Lower the head of bed", "Delay care until rounds"],
    answer: "Assess airway patency",
    rationale: "A tracheostomy is an artificial airway. Restlessness and noisy respirations may indicate obstruction, so airway patency is the priority."
  },
  {
    id: "TRACH-002",
    caseId: "TRACH-CASE-001",
    patient: "Mr. Carl Simmons",
    topic: "Tracheostomy",
    subtopic: "Suctioning",
    style: "Take Action",
    difficulty: "ATI",
    question: "Mr. Simmons has coarse breath sounds and visible secretions in the tracheostomy. Which action should the nurse anticipate?",
    choices: ["Suction the tracheostomy using sterile technique", "Clamp the tracheostomy", "Remove oxygen permanently", "Give oral fluids through the trach"],
    answer: "Suction the tracheostomy using sterile technique",
    rationale: "Suctioning clears secretions from the artificial airway. Sterile technique helps reduce infection risk."
  },
  {
    id: "TRACH-003",
    caseId: "TRACH-CASE-002",
    patient: "Ms. Janet Price",
    topic: "Tracheostomy",
    subtopic: "Emergency Equipment",
    style: "Safety",
    difficulty: "ATI",
    question: "Which equipment should be kept at the bedside for Ms. Price with a tracheostomy?",
    choices: ["Obturator and replacement tracheostomy tubes", "Extra meal trays", "Heating pad", "Incentive spirometer only"],
    answer: "Obturator and replacement tracheostomy tubes",
    rationale: "Emergency tracheostomy equipment should be available in case the tube becomes displaced or obstructed."
  },
  {
    id: "TRACH-004",
    caseId: "TRACH-CASE-002",
    patient: "Ms. Janet Price",
    topic: "Tracheostomy",
    subtopic: "Dislodgement",
    style: "Priority",
    difficulty: "ATI",
    question: "Ms. Price's tracheostomy tube becomes dislodged and she is in respiratory distress. What is the nurse's priority?",
    choices: ["Call for help and maintain airway", "Document the event only", "Offer ice chips", "Wait for the provider to round"],
    answer: "Call for help and maintain airway",
    rationale: "A dislodged tracheostomy can quickly become life-threatening. The priority is maintaining airway and getting immediate assistance."
  },
  {
    id: "TRACH-005",
    caseId: "TRACH-CASE-003",
    patient: "Mr. Joseph Lee",
    topic: "Tracheostomy",
    subtopic: "Humidification",
    style: "Application",
    difficulty: "Basic",
    question: "Mr. Lee has thick secretions from his tracheostomy. Which intervention may help loosen secretions?",
    choices: ["Provide humidification as prescribed", "Withhold all fluids", "Keep the patient flat", "Avoid suctioning forever"],
    answer: "Provide humidification as prescribed",
    rationale: "Artificial airways bypass normal humidification. Humidification helps keep secretions moist and easier to clear."
  },
  {
    id: "TRACH-006",
    caseId: "TRACH-CASE-003",
    patient: "Mr. Joseph Lee",
    topic: "Tracheostomy",
    subtopic: "Assessment",
    style: "Analyze Cues",
    difficulty: "ATI",
    question: "Which finding suggests Mr. Lee may need tracheostomy suctioning?",
    choices: ["Coarse breath sounds and increased work of breathing", "Clear lung sounds", "Improved oxygen saturation", "Calm breathing"],
    answer: "Coarse breath sounds and increased work of breathing",
    rationale: "Coarse breath sounds, visible secretions, decreased oxygen saturation, or increased work of breathing may indicate the need for suctioning."
  },
  {
    id: "TRACH-007",
    caseId: "TRACH-CASE-004",
    patient: "Ms. Brenda Hall",
    topic: "Tracheostomy",
    subtopic: "Infection Prevention",
    style: "Safety",
    difficulty: "ATI",
    question: "Which nursing action helps prevent infection during tracheostomy care?",
    choices: ["Use sterile technique for suctioning", "Reuse dirty suction catheters", "Avoid hand hygiene", "Leave secretions on the skin"],
    answer: "Use sterile technique for suctioning",
    rationale: "Sterile technique during suctioning helps reduce infection risk in patients with artificial airways."
  },
  {
    id: "TRACH-008",
    caseId: "TRACH-CASE-004",
    patient: "Ms. Brenda Hall",
    topic: "Tracheostomy",
    subtopic: "Skin Care",
    style: "Take Action",
    difficulty: "Basic",
    question: "Ms. Hall has moisture and drainage around the tracheostomy site. What should the nurse do?",
    choices: ["Clean and dry the site per policy", "Ignore it", "Apply food-grade oil", "Remove the tracheostomy tube"],
    answer: "Clean and dry the site per policy",
    rationale: "Tracheostomy site care helps prevent skin breakdown and infection."
  },
  {
    id: "TRACH-009",
    caseId: "TRACH-CASE-005",
    patient: "Mr. Raymond Carter",
    topic: "Tracheostomy",
    subtopic: "Communication",
    style: "Teaching",
    difficulty: "Basic",
    question: "Mr. Carter is unable to speak after tracheostomy placement. Which nursing action supports communication?",
    choices: ["Provide a communication board or writing tool", "Ignore attempts to communicate", "Tell him not to communicate", "Remove the tracheostomy"],
    answer: "Provide a communication board or writing tool",
    rationale: "Patients with a tracheostomy may need alternative communication methods until speaking options are appropriate."
  },
  {
    id: "TRACH-010",
    caseId: "TRACH-CASE-005",
    patient: "Mr. Raymond Carter",
    topic: "Tracheostomy",
    subtopic: "Psychosocial",
    style: "Analyze Cues",
    difficulty: "ATI",
    question: "Mr. Carter appears anxious because he cannot speak. What is the best nursing response?",
    choices: ["Stay calm and provide a way to communicate", "Leave the room", "Tell him anxiety is not important", "Delay all explanations"],
    answer: "Stay calm and provide a way to communicate",
    rationale: "Anxiety can increase respiratory distress. Reassurance and communication support promote safety and comfort."
  },
  {
    id: "TRACH-011",
    caseId: "TRACH-CASE-006",
    patient: "Ms. Olivia Grant",
    topic: "Tracheostomy",
    subtopic: "Evaluation",
    style: "Evaluation",
    difficulty: "ATI",
    question: "Which finding shows Ms. Grant's airway clearance is improving after suctioning?",
    choices: ["Breath sounds are clearer", "SpO₂ decreases", "Respirations become more labored", "Secretions increase and block airflow"],
    answer: "Breath sounds are clearer",
    rationale: "Clearer breath sounds, improved oxygen saturation, and reduced work of breathing indicate effective airway clearance."
  },
  {
    id: "TRACH-012",
    caseId: "TRACH-CASE-006",
    patient: "Ms. Olivia Grant",
    topic: "Tracheostomy",
    subtopic: "Complication",
    style: "Priority",
    difficulty: "ATI",
    question: "After suctioning, Ms. Grant's SpO₂ drops and she becomes cyanotic. What should the nurse do first?",
    choices: ["Stop suctioning and oxygenate the patient", "Continue suctioning longer", "Offer oral fluids", "Document only"],
    answer: "Stop suctioning and oxygenate the patient",
    rationale: "Suctioning can cause hypoxemia. If oxygen saturation drops or cyanosis occurs, stop suctioning and provide oxygenation support."
  },
  {
    id: "TRACH-013",
    caseId: "TRACH-CASE-007",
    patient: "Mr. Ethan Moore",
    topic: "Tracheostomy",
    subtopic: "Teaching",
    style: "Teaching",
    difficulty: "Basic",
    question: "Mr. Moore is going home with a tracheostomy. Which statement shows correct understanding?",
    choices: ["I should keep emergency supplies nearby", "I should ignore trouble breathing", "I should remove the tube daily without instruction", "I do not need to clean the site"],
    answer: "I should keep emergency supplies nearby",
    rationale: "Patients with a tracheostomy need emergency supplies available and should know when to seek help."
  },
  {
    id: "TRACH-014",
    caseId: "TRACH-CASE-007",
    patient: "Mr. Ethan Moore",
    topic: "Tracheostomy",
    subtopic: "Emergency Teaching",
    style: "Safety",
    difficulty: "ATI",
    question: "Which symptom should Mr. Moore report immediately?",
    choices: ["Sudden difficulty breathing", "Mild thirst", "Slight hunger", "Boredom"],
    answer: "Sudden difficulty breathing",
    rationale: "Sudden difficulty breathing may indicate obstruction, displacement, or respiratory distress and requires immediate attention."
  },
  {
    id: "TRACH-015",
    caseId: "TRACH-CASE-008",
    patient: "Ms. Hannah Smith",
    topic: "Tracheostomy",
    subtopic: "SATA",
    style: "SATA",
    difficulty: "ATI",
    question: "Which actions are appropriate for a patient with a tracheostomy? Select all that apply.",
    choices: ["Keep emergency equipment at bedside", "Assess breath sounds", "Suction when clinically indicated", "Use sterile technique for suctioning", "Ignore signs of obstruction"],
    answer: ["Keep emergency equipment at bedside", "Assess breath sounds", "Suction when clinically indicated", "Use sterile technique for suctioning"],
    rationale: "Tracheostomy care includes airway assessment, emergency equipment, suctioning when needed, and infection prevention."
  }
];